"""Independent oracle for EVM golden block 26000004.

Decodes the unchanged raw payload with Python protobuf (descriptor generated by
protoc from proto/ethereum.proto) and applies the documented output rules:
- rows are emitted in transaction, call and recording order;
- a SUCCEEDED transaction writes every call's state changes;
- a FAILED/REVERTED transaction writes only the root call's GAS_BUY,
  GAS_REFUND, REWARD_TRANSACTION_FEE and INCREASE_MINT balance changes, the
  earliest (ordinal, then recording order) nonce change, and for each accepted
  (non-discarded) EIP-7702 authorization the earliest remaining nonce and code
  change of its authority; all gas changes are kept; no storage/account rows.
It never imports or runs the Rust mapper.

Usage (Python with the `protobuf` package, and `protoc` on PATH):

    protoc -I proto --include_imports --descriptor_set_out=/tmp/eth.desc proto/ethereum.proto
    zstd -dc blocks/tests/fixtures/evm-mainnet-26000004/block.pb.zst > /tmp/block.pb
    python3 docs/audit/499-evm-golden-oracle.py /tmp/eth.desc /tmp/block.pb /tmp/expected.json
    diff /tmp/expected.json blocks/tests/fixtures/evm-mainnet-26000004/expected.json
"""
import json
import sys
from google.protobuf import descriptor_pb2, descriptor_pool, message_factory

fds = descriptor_pb2.FileDescriptorSet()
fds.ParseFromString(open(sys.argv[1], 'rb').read())
pool = descriptor_pool.DescriptorPool()
for f in fds.file:
    pool.Add(f)
Block = message_factory.GetMessageClass(pool.FindMessageTypeByName('sf.ethereum.type.v2.Block'))
b = Block()
b.ParseFromString(open(sys.argv[2], 'rb').read())

REASON = pool.FindEnumTypeByName('sf.ethereum.type.v2.BalanceChange.Reason')
TXTYPE = pool.FindEnumTypeByName('sf.ethereum.type.v2.TransactionTrace.Type')
STATUS = pool.FindEnumTypeByName('sf.ethereum.type.v2.TransactionTraceStatus')
CALLTYPE = pool.FindEnumTypeByName('sf.ethereum.type.v2.CallType')
SUCCEEDED = STATUS.values_by_name['SUCCEEDED'].number
KEEP = {REASON.values_by_name[n].number for n in
        ['REASON_GAS_BUY', 'REASON_GAS_REFUND', 'REASON_REWARD_TRANSACTION_FEE', 'REASON_INCREASE_MINT']}


def hx(v):
    return '0x' + v.hex()


def dec(v):
    return str(int.from_bytes(v, 'big'))


def big(msg, field):
    # Present BigInt -> decimal of its bytes; absent -> None.
    return dec(getattr(msg, field).bytes) if msg.HasField(field) else None


def strip(name, prefix):
    return name[len(prefix):] if name.startswith(prefix) else name


def order(items):
    return sorted(range(len(items)), key=lambda i: (items[i].ordinal, i))


def persistent(t):
    root = t.calls[0]
    bcs = [bc for bc in root.balance_changes if bc.reason in KEEP]
    nord, cord = order(root.nonce_changes), order(root.code_changes)
    kn = nord[:1]
    kc = []
    for a in t.set_code_authorizations:
        if a.discarded or not a.HasField('authority') or not a.authority:
            continue
        for i in nord:
            if root.nonce_changes[i].address == a.authority and i not in kn:
                kn.append(i)
                break
        for i in cord:
            if root.code_changes[i].address == a.authority and i not in kc:
                kc.append(i)
                break
    return (bcs, [root.nonce_changes[i] for i in sorted(kn)], [root.code_changes[i] for i in sorted(kc)])


rows = {k: [] for k in [
    'blocks', 'transactions', 'logs', 'withdrawals', 'access_lists', 'set_code_authorizations', 'calls',
    'balance_changes', 'nonce_changes', 'storage_changes', 'code_changes', 'gas_changes', 'account_creations',
    'system_balance_changes', 'system_code_changes', 'system_storage_changes', 'system_nonce_changes',
    'system_gas_changes', 'system_account_creations', 'system_calls']}
rows['blocks'].append(('Block and Block.header', b))
rows['withdrawals'] = [(f'Block.withdrawals[{i}]', w) for i, w in enumerate(b.withdrawals)]
for ti, t in enumerate(b.transaction_traces):
    tp = f'Block.transaction_traces[{ti}]'
    rows['transactions'].append((tp, t))
    rows['access_lists'] += [(f'{tp}.access_list[{i}]', a) for i, a in enumerate(t.access_list)]
    rows['set_code_authorizations'] += [(f'{tp}.set_code_authorizations[{i}]', (t, i, a))
                                        for i, a in enumerate(t.set_code_authorizations)]
    rows['logs'] += [(f'{tp}.receipt.logs[{i}]', l) for i, l in enumerate(t.receipt.logs)]
    rows['calls'] += [(f'{tp}.calls[{i}]', (t, c)) for i, c in enumerate(t.calls)]
    if t.status == SUCCEEDED:
        for ci, c in enumerate(t.calls):
            cp = f'{tp}.calls[{ci}]'
            for f in ['balance_changes', 'code_changes', 'storage_changes', 'nonce_changes', 'gas_changes',
                      'account_creations']:
                rows[f] += [(f'{cp}.{f}[{i}]', (t, c, x)) for i, x in enumerate(getattr(c, f))]
    else:
        root = t.calls[0]
        bcs, ncs, ccs = persistent(t)
        cp = f'{tp}.calls[0]'
        rows['balance_changes'] += [(f'{cp}.balance_changes[{list(root.balance_changes).index(x)}]', (t, root, x)) for x in bcs]
        rows['nonce_changes'] += [(f'{cp}.nonce_changes[{list(root.nonce_changes).index(x)}]', (t, root, x)) for x in ncs]
        rows['code_changes'] += [(f'{cp}.code_changes[{list(root.code_changes).index(x)}]', (t, root, x)) for x in ccs]
        for ci, c in enumerate(t.calls):
            rows['gas_changes'] += [(f'{tp}.calls[{ci}].gas_changes[{i}]', (t, c, x)) for i, x in enumerate(c.gas_changes)]
rows['system_balance_changes'] += [(f'Block.balance_changes[{i}]', x) for i, x in enumerate(b.balance_changes)]
rows['system_code_changes'] += [(f'Block.code_changes[{i}]', x) for i, x in enumerate(b.code_changes)]
for si, sc in enumerate(b.system_calls):
    rows['system_calls'].append((f'Block.system_calls[{si}]', sc))
    for f in ['balance_changes', 'code_changes', 'storage_changes', 'nonce_changes', 'gas_changes', 'account_creations']:
        rows['system_' + f] += [(f'Block.system_calls[{si}].{f}[{i}]', x) for i, x in enumerate(getattr(sc, f))]

counts = {k: len(v) for k, v in sorted(rows.items())}


def find(table, pred):
    hits = [i for i, (_, x) in enumerate(rows[table]) if pred(x)]
    return hits


h = b.header
selections = [{
    'table': 'blocks', 'row': 0, 'source': 'Block and Block.header', 'values': {
        'number': b.number, 'hash': hx(b.hash), 'parent_hash': hx(h.parent_hash), 'gas_used': h.gas_used,
        'gas_limit': h.gas_limit, 'base_fee_per_gas': big(h, 'base_fee_per_gas'), 'coinbase': hx(h.coinbase),
        'num_transactions': len(b.transaction_traces),
        'detail_level': strip(pool.FindEnumTypeByName('sf.ethereum.type.v2.Block.DetailLevel').values_by_number[b.detail_level].name, 'DETAILLEVEL_'),
        'blob_gas_used': h.blob_gas_used if h.HasField('blob_gas_used') else None,
        'excess_blob_gas': h.excess_blob_gas if h.HasField('excess_blob_gas') else None,
        'withdrawals_root': hx(h.withdrawals_root), 'parent_beacon_root': hx(h.parent_beacon_root),
        'requests_hash': hx(h.requests_hash)}}]


def tx_sel(ti):
    t = b.transaction_traces[ti]
    return {'table': 'transactions', 'row': ti, 'source': f'Block.transaction_traces[{ti}]', 'values': {
        'index': t.index, 'hash': hx(t.hash), 'from': hx(getattr(t, 'from')), 'to': hx(t.to),
        'value': big(t, 'value') or '0', 'gas_limit': t.gas_limit, 'gas_price': big(t, 'gas_price'),
        'type': strip(TXTYPE.values_by_number[t.type].name, 'TRX_TYPE_'),
        'status': STATUS.values_by_number[t.status].name, 'gas_used': t.gas_used, 'nonce': t.nonce,
        'max_fee_per_gas': big(t, 'max_fee_per_gas'),
        'max_priority_fee_per_gas': big(t, 'max_priority_fee_per_gas'),
        'cumulative_gas_used': t.receipt.cumulative_gas_used, 'blob_gas': t.blob_gas if t.HasField('blob_gas') else None,
        'blob_hashes': [hx(x) for x in t.blob_hashes],
        'begin_ordinal': t.begin_ordinal, 'end_ordinal': t.end_ordinal}}


selections += [tx_sel(130), tx_sel(193)]

for ti in [118, 130, 331, 358]:
    for r in find('set_code_authorizations', lambda x: x[0].index == ti):
        src, (t, i, a) = rows['set_code_authorizations'][r]
        if ti == 331 and i not in (0, 8):
            continue
        selections.append({'table': 'set_code_authorizations', 'row': r, 'source': src, 'values': {
            'tx_hash': hx(t.hash), 'tx_index': t.index, 'authorization_index': i, 'chain_id': dec(a.chain_id),
            'address': hx(a.address) if a.address else None, 'nonce': a.nonce, 'v': a.v, 'r': hx(a.r), 's': hx(a.s),
            'authority': hx(a.authority) if a.HasField('authority') and a.authority else None,
            'discarded': a.discarded}})

for r in find('calls', lambda x: x[0].index == 130):
    src, (t, c) = rows['calls'][r]
    selections.append({'table': 'calls', 'row': r, 'source': src, 'values': {
        'tx_hash': hx(t.hash), 'tx_index': t.index, 'call_index': c.index, 'parent_index': c.parent_index,
        'depth': c.depth, 'call_type': CALLTYPE.values_by_number[c.call_type].name, 'caller': hx(c.caller),
        'address': hx(c.address), 'value': big(c, 'value') or '0', 'state_reverted': c.state_reverted,
        'status_reverted': c.status_reverted, 'status_failed': c.status_failed,
        'begin_ordinal': c.begin_ordinal, 'end_ordinal': c.end_ordinal}})
    break


def change_ctx(t, c):
    return {'tx_hash': hx(t.hash), 'tx_index': t.index, 'call_index': c.index, 'state_reverted': c.state_reverted,
            'persisted': (t.status != SUCCEEDED) or (not c.state_reverted)}


for ti in [130, 193]:
    for r in find('balance_changes', lambda x: x[0].index == ti):
        src, (t, c, x) = rows['balance_changes'][r]
        v = change_ctx(t, c)
        v.update({'ordinal': x.ordinal, 'address': hx(x.address), 'old_value': dec(x.old_value.bytes),
                  'new_value': dec(x.new_value.bytes), 'reason': strip(REASON.values_by_number[x.reason].name, 'REASON_')})
        selections.append({'table': 'balance_changes', 'row': r, 'source': src, 'values': v})
    for r in find('nonce_changes', lambda x: x[0].index == ti):
        src, (t, c, x) = rows['nonce_changes'][r]
        v = change_ctx(t, c)
        v.update({'ordinal': x.ordinal, 'address': hx(x.address), 'old_value': x.old_value, 'new_value': x.new_value})
        selections.append({'table': 'nonce_changes', 'row': r, 'source': src, 'values': v})

for r, (src, (t, c, x)) in enumerate(rows['code_changes']):
    if len(x.new_code) > 64:
        continue
    v = change_ctx(t, c)
    v.update({'ordinal': x.ordinal, 'address': hx(x.address), 'old_hash': hx(x.old_hash), 'new_hash': hx(x.new_hash),
              'old_code': hx(x.old_code), 'new_code': hx(x.new_code)})
    selections.append({'table': 'code_changes', 'row': r, 'source': src, 'values': v})

out = {'format_version': 1, 'counts': counts, 'selections': selections}
with open(sys.argv[3], 'w') as fh:
    json.dump(out, fh, indent=2)
    fh.write('\n')
print(json.dumps(counts))
print('selections', len(selections), 'values', sum(len(s['values']) for s in selections),
      'extended rows', sum(counts.values()))
for s in selections:
    print(s['table'], s['row'], s['source'])
