[workspace]
resolver = "2"
members = [
    "crates/firehose-protos",
    "crates/firehose-parquet",
    "crates/firehose-solana-to-parquet",
    "crates/firehose-evm-to-parquet",
    "crates/firehose-bitcoin-to-parquet",
    "crates/firehose-near-to-parquet",
    "crates/firehose-antelope-to-parquet",
    "crates/firehose-cosmos-to-parquet",
    "crates/firehose-tron-to-parquet",
    "crates/firehose-beacon-to-parquet",
]
