[package]
name = "blocks"
version.workspace = true
edition.workspace = true
description = "Block type definitions for all Firehose chain types"

[lib]
name = "blocks"
path = "src/lib.rs"

[[bin]]
name = "firehose-parquet"
path = "src/bin/main.rs"

[dependencies]
firehose-parquet = { path = "../firehose-parquet" }
firehose-protos = { path = "../firehose-protos" }
arrow.workspace = true
prost.workspace = true
prost-types.workspace = true
tokio.workspace = true
clap.workspace = true
tracing.workspace = true
anyhow.workspace = true
sha2.workspace = true
prometheus-client.workspace = true
time = { version = "0.3", features = ["formatting"] }
serde_json = "1"
