[package]
name = "firehose-protos"
version = "0.2.5"
edition = "2021"
description = "Compiled protobuf definitions for all Firehose chain types"

[dependencies]
prost.workspace = true
prost-types.workspace = true
tonic = { workspace = true, features = ["transport"] }
tonic-prost = "0.14"

[build-dependencies]
tonic-prost-build = "0.14"
