// @generated by scripts/generate_networks.rs. Do not edit by hand.
// Source: The Graph networks registry (v0.8.4, updatedAt 2026-09-24T21:50:40.258Z).
// Refresh steps: docs/network-registry-integration.md

use crate::networks::BuiltinNetwork;

pub const GENERATED_NETWORKS: &[BuiltinNetwork] = &[
    BuiltinNetwork {
        chain_name: "arbitrum-one",
        default_endpoint: "https://arbone.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "arbitrum-sepolia",
        default_endpoint: "https://arbsepolia.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "arc",
        default_endpoint: "https://arc.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "avalanche",
        default_endpoint: "https://avalanche.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "base",
        default_endpoint: "https://base.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "base-sepolia",
        default_endpoint: "https://basesepolia.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "blast-mainnet",
        default_endpoint: "https://blast.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "bsc",
        default_endpoint: "https://bsc.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "btc",
        default_endpoint: "https://bitcoin.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "celo",
        default_endpoint: "https://celo.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "chapel",
        default_endpoint: "https://chapel.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "eos",
        default_endpoint: "https://eos.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "gnosis-cl",
        default_endpoint: "https://gnosis-cl.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "hoodi",
        default_endpoint: "https://hoodi.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "hoodi-cl",
        default_endpoint: "https://hoodi-cl.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "hyper-evm",
        default_endpoint: "https://hyperevm.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "ink",
        default_endpoint: "https://ink.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "jungle4",
        default_endpoint: "https://jungle4.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "linea",
        default_endpoint: "https://linea.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "linea-sepolia",
        default_endpoint: "https://lineasepolia.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "litecoin",
        default_endpoint: "https://litecoin.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "mainnet",
        default_endpoint: "https://eth.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "mainnet-cl",
        default_endpoint: "https://eth-cl.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "matic",
        default_endpoint: "https://polygon.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "megaeth",
        default_endpoint: "https://megaeth.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "near-mainnet",
        default_endpoint: "https://mainnet.near.streamingfast.io:443",
    },
    BuiltinNetwork {
        chain_name: "near-testnet",
        default_endpoint: "https://testnet.near.streamingfast.io:443",
    },
    BuiltinNetwork {
        chain_name: "optimism",
        default_endpoint: "https://optimism.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "optimism-sepolia",
        default_endpoint: "https://opsepolia.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "polygon-amoy",
        default_endpoint: "https://amoy.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "robinhood",
        default_endpoint: "https://robinhood.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "sepolia",
        default_endpoint: "https://sepolia.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "sepolia-cl",
        default_endpoint: "https://sepolia-cl.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "solana-devnet",
        default_endpoint: "https://soldev.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "solana-mainnet-beta",
        default_endpoint: "https://solana.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "soneium",
        default_endpoint: "https://soneium.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "soneium-testnet",
        default_endpoint: "https://minato.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "tempo",
        default_endpoint: "https://tempo.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "tron",
        default_endpoint: "https://mainnet.tron.streamingfast.io:443",
    },
    BuiltinNetwork {
        chain_name: "tron-evm",
        default_endpoint: "https://mainnet-evm.tron.streamingfast.io:443",
    },
    BuiltinNetwork {
        chain_name: "unichain",
        default_endpoint: "https://unichain.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "unichain-testnet",
        default_endpoint: "https://unisepolia.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "wax",
        default_endpoint: "https://wax.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "wax-testnet",
        default_endpoint: "https://waxtest.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "xlayer-mainnet",
        default_endpoint: "https://xlayer.firehose.pinax.network:443",
    },
    BuiltinNetwork {
        chain_name: "zora",
        default_endpoint: "https://zora.firehose.pinax.network:443",
    },
];

pub const GENERATED_NETWORK_NAMES: &[&str] = &[
    "arbitrum-one",
    "arbitrum-sepolia",
    "arc",
    "avalanche",
    "base",
    "base-sepolia",
    "blast-mainnet",
    "bsc",
    "btc",
    "celo",
    "chapel",
    "eos",
    "gnosis-cl",
    "hoodi",
    "hoodi-cl",
    "hyper-evm",
    "ink",
    "jungle4",
    "linea",
    "linea-sepolia",
    "litecoin",
    "mainnet",
    "mainnet-cl",
    "matic",
    "megaeth",
    "near-mainnet",
    "near-testnet",
    "optimism",
    "optimism-sepolia",
    "polygon-amoy",
    "robinhood",
    "sepolia",
    "sepolia-cl",
    "solana-devnet",
    "solana-mainnet-beta",
    "soneium",
    "soneium-testnet",
    "tempo",
    "tron",
    "tron-evm",
    "unichain",
    "unichain-testnet",
    "wax",
    "wax-testnet",
    "xlayer-mainnet",
    "zora",
];
