//! Table specs generated from the final specification §3 (`final-spec.md`).
//! Edit only to fix a divergence from the specification; regenerate
//! `docs/schemas/sec.md` and re-pin the chain schema digests afterwards.

#[allow(unused_imports)]
use super::{Col, Family, Member, TableSpec, Ty};

/// §3.17 `beneficial_reports`.
pub(crate) const BENEFICIAL_REPORTS: TableSpec = TableSpec {
    name: super::BENEFICIAL_REPORTS,
    doc: "Beneficial-ownership (13D/13G) filings with the structured items; legacy SC 13D/G rows carry metadata only.",
    filing_context: true,
    cols: &[
        Col::new(
            "subject_company_cik",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.subject_company_cik`. Issuer of the class.",
        ),
        Col::new(
            "subject_company_name",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.subject_company_name`.",
        ),
        Col::new(
            "cusip",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.cusip`. = cusips[0].",
        ),
        Col::new(
            "cusips",
            Ty::ListUtf8,
            false,
            "`Filing.body.beneficial.cusips[]`: verbatim items in document order; [] when empty. Every issuer CUSIP (2025+ repeatable shape).",
        ),
        Col::new(
            "cusip_norm",
            Ty::Utf8,
            true,
            "Derived from `Filing.body.beneficial.cusip`: §4.4 `cusip_norm`.",
        ),
        Col::new(
            "schedule_type",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.schedule_type`. `SCHEDULE 13G/A`, legacy `SC 13D`…",
        ),
        Col::new(
            "schedule_kind",
            Ty::Dictionary,
            true,
            "Derived from `Filing.body.beneficial.schedule_type`: `13D` if schedule_type (else form_type) contains 13D; `13G` if 13G. 13D = active intent, 13G = passive.",
        ),
        Col::new(
            "filer_cik",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.filer_cik`. NULL on legacy SC 13D/G.",
        ),
        Col::new(
            "securities_class_title",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.securities_class_title`.",
        ),
        Col::new(
            "event_date",
            Ty::Date32,
            true,
            "`Filing.body.beneficial.event_date`: date (§4.2).",
        ),
        Col::new(
            "issuer_street1",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.issuer_address.street1`.",
        ),
        Col::new(
            "issuer_street2",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.issuer_address.street2`.",
        ),
        Col::new(
            "issuer_city",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.issuer_address.city`.",
        ),
        Col::new(
            "issuer_state",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.issuer_address.state`. EDGAR state/country code.",
        ),
        Col::new(
            "issuer_zip_code",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.issuer_address.zip_code`. Text (keeps leading zeros).",
        ),
        Col::new(
            "issuer_state_description",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.issuer_address.state_description`. Filled only by Forms 3/4/5 and D.",
        ),
        Col::new(
            "issuer_country",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.issuer_address.country`.",
        ),
        Col::new(
            "issuer_non_us_state_territory",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.issuer_address.non_us_state_territory`.",
        ),
        Col::new(
            "rules_designated",
            Ty::ListUtf8,
            false,
            "`Filing.body.beneficial.rules_designated[]`: verbatim items in document order; [] when empty. `Rule 13d-1(b)` QII / `(c)` passive / `(d)` exempt.",
        ),
        Col::new(
            "previous_accession_number",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.previous_accession_number`. Kept on originals too (envelope copies it only onto amendments).",
        ),
        Col::new(
            "amendment_number",
            Ty::Int32,
            true,
            "`Filing.body.beneficial.amendment_number`: integer (§4.3), Int32.",
        ),
        Col::new(
            "previously_filed",
            Ty::Boolean,
            true,
            "`Filing.body.beneficial.previously_filed`: optional bool: NULL when unset. 13D.",
        ),
        Col::new(
            "item13d_security_title",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13d.security_title`.",
        ),
        Col::new(
            "item13d_issuer_name",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13d.issuer_name`.",
        ),
        Col::new(
            "item13d_issuer_principal_street1",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13d.issuer_principal_address.street1`.",
        ),
        Col::new(
            "item13d_issuer_principal_street2",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13d.issuer_principal_address.street2`.",
        ),
        Col::new(
            "item13d_issuer_principal_city",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13d.issuer_principal_address.city`.",
        ),
        Col::new(
            "item13d_issuer_principal_state",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13d.issuer_principal_address.state`. EDGAR state/country code.",
        ),
        Col::new(
            "item13d_issuer_principal_zip_code",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13d.issuer_principal_address.zip_code`. Text (keeps leading zeros).",
        ),
        Col::new(
            "item13d_issuer_principal_state_description",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13d.issuer_principal_address.state_description`. Filled only by Forms 3/4/5 and D.",
        ),
        Col::new(
            "item13d_issuer_principal_country",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13d.issuer_principal_address.country`.",
        ),
        Col::new(
            "item13d_issuer_principal_non_us_state_territory",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13d.issuer_principal_address.non_us_state_territory`.",
        ),
        Col::new(
            "item13d_item1_comment",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13d.item1_comment`.",
        ),
        Col::new(
            "item13d_filing_person_name",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13d.filing_person_name`.",
        ),
        Col::new(
            "item13d_principal_business_address",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13d.principal_business_address`. Free text.",
        ),
        Col::new(
            "item13d_principal_job",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13d.principal_job`.",
        ),
        Col::new(
            "item13d_has_been_convicted",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13d.has_been_convicted`. Free text answer.",
        ),
        Col::new(
            "item13d_conviction_description",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13d.conviction_description`.",
        ),
        Col::new(
            "item13d_citizenship",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13d.citizenship`.",
        ),
        Col::new(
            "item13d_funds_source",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13d.funds_source`. Item 3.",
        ),
        Col::new(
            "item13d_transaction_purpose",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13d.transaction_purpose`. Item 4: purpose of transaction (activist intent).",
        ),
        Col::new(
            "item13d_percentage_of_class",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13d.percentage_of_class`. Item 5 free text.",
        ),
        Col::new(
            "item13d_number_of_shares",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13d.number_of_shares`. Item 5 free text.",
        ),
        Col::new(
            "item13d_transaction_description",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13d.transaction_description`. Item 5(c).",
        ),
        Col::new(
            "item13d_list_of_shareholders",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13d.list_of_shareholders`.",
        ),
        Col::new(
            "item13d_date_5_percent_ownership",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13d.date_5_percent_ownership`. Free text (`Not applicable.`).",
        ),
        Col::new(
            "item13d_contract_description",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13d.contract_description`. Item 6.",
        ),
        Col::new(
            "item13d_filed_exhibits",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13d.filed_exhibits`. Item 7.",
        ),
        Col::new(
            "item13g_type_of_person_filing",
            Ty::ListUtf8,
            false,
            "`Filing.body.beneficial.items_13g.type_of_person_filing[]`: verbatim items in document order; [] when empty. `IA`, `HC`, `BD`…",
        ),
        Col::new(
            "item13g_other_type_of_person_filing",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13g.other_type_of_person_filing`.",
        ),
        Col::new(
            "item13g_amount_beneficially_owned",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13g.amount_beneficially_owned`. Free text (often \"see cover page\"); typed values are on persons.",
        ),
        Col::new(
            "item13g_class_percent",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13g.class_percent`. Free text.",
        ),
        Col::new(
            "item13g_sole_voting_power",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13g.sole_voting_power`. Free text.",
        ),
        Col::new(
            "item13g_shared_voting_power",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13g.shared_voting_power`. Free text.",
        ),
        Col::new(
            "item13g_sole_dispositive_power",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13g.sole_dispositive_power`. Free text.",
        ),
        Col::new(
            "item13g_shared_dispositive_power",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13g.shared_dispositive_power`. Free text.",
        ),
        Col::new(
            "item13g_class_ownership_5_percent_or_less",
            Ty::Boolean,
            true,
            "`Filing.body.beneficial.items_13g.class_ownership_5_percent_or_less`: optional bool: NULL when unset. Exit below 5%.",
        ),
        Col::new(
            "item13g_ownership_on_behalf_of_another",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13g.ownership_on_behalf_of_another`.",
        ),
        Col::new(
            "item13g_subsidiary_identification",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13g.subsidiary_identification`.",
        ),
        Col::new(
            "item13g_group_members_identification",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13g.group_members_identification`.",
        ),
        Col::new(
            "item13g_group_dissolution_notice",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13g.group_dissolution_notice`.",
        ),
        Col::new(
            "item13g_certifications",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13g.certifications`.",
        ),
        Col::new(
            "item13g_issuer_name",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13g.issuer_name`.",
        ),
        Col::new(
            "item13g_issuer_principal_office_address",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13g.issuer_principal_office_address`. Free text.",
        ),
        Col::new(
            "item13g_filing_person_name",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13g.filing_person_name`. Free text.",
        ),
        Col::new(
            "item13g_principal_business_office_address",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13g.principal_business_office_address`. Free text.",
        ),
        Col::new(
            "item13g_citizenship",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.items_13g.citizenship`.",
        ),
        Col::new(
            "exhibit_info",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.exhibit_info`. E.g. joint filing agreement.",
        ),
        Col::new(
            "signature_comments",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.signature_comments`.",
        ),
        Col::new(
            "authorized_persons",
            Ty::ListStruct(&[("name", Member::Utf8), ("phone", Member::Utf8), ("street1", Member::Utf8), ("street2", Member::Utf8), ("city", Member::Utf8), ("state", Member::Utf8), ("zip_code", Member::Utf8), ("state_description", Member::Utf8), ("country", Member::Utf8), ("non_us_state_territory", Member::Utf8)]),
            false,
            "`Filing.body.beneficial.authorized_persons[]`: one struct per element (name, phone, address.* flattened), verbatim ('' → NULL); [] when empty. 13D cover: persons authorized to receive notices.",
        ),
        Col::new(
            "reporting_person_count",
            Ty::UInt32,
            false,
            "Derived from `Filing.body.beneficial.reporting_persons[]`: length of the list. 0 = legacy or metadata-only filing.",
        ),
        Col::new(
            "max_aggregate_amount_owned",
            Ty::Decimal(Family::Q6),
            true,
            "Derived from `Filing.body.beneficial.reporting_persons[].aggregate_amount_owned`: max over the persons' non-NULL typed values; NULL when there are none. The stake; never SUM persons (group members repeat the same shares).",
        ),
        Col::new(
            "max_percent_of_class",
            Ty::Decimal(Family::R12),
            true,
            "Derived from `Filing.body.beneficial.reporting_persons[].percent_of_class`: max over the persons' non-NULL typed values; NULL when there are none. Percent units.",
        ),
        Col::new(
            "signature_count",
            Ty::UInt32,
            false,
            "Derived from `Filing.body.beneficial.signatures[]`: length of the list.",
        ),
        Col::new(
            "has_parse_issues",
            Ty::Boolean,
            false,
            "Derived: true iff this row wrote ≥1 `parse_issues` row (§4.6).",
        ),
    ],
};

/// §3.18 `beneficial_reporting_persons`.
pub(crate) const BENEFICIAL_REPORTING_PERSONS: TableSpec = TableSpec {
    name: super::BENEFICIAL_REPORTING_PERSONS,
    doc: "Cover-page rows of a 13D/G: one per reporting person, with typed share counts and percent.",
    filing_context: true,
    cols: &[
        Col::new(
            "subject_company_cik",
            Ty::Utf8,
            true,
            "Copy of `beneficial_reports.subject_company_cik`.",
        ),
        Col::new(
            "subject_company_name",
            Ty::Utf8,
            true,
            "Copy of `beneficial_reports.subject_company_name`.",
        ),
        Col::new(
            "cusip_norm",
            Ty::Utf8,
            true,
            "Copy of `beneficial_reports.cusip_norm`.",
        ),
        Col::new(
            "schedule_kind",
            Ty::Dictionary,
            true,
            "Copy of `beneficial_reports.schedule_kind`.",
        ),
        Col::new(
            "event_date",
            Ty::Date32,
            true,
            "Copy of `beneficial_reports.event_date`.",
        ),
        Col::new(
            "person_index",
            Ty::UInt32,
            false,
            "Derived: position in `reporting_persons`.",
        ),
        Col::new(
            "person_cik",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.reporting_persons[].cik`. Mostly NULL (13G has none).",
        ),
        Col::new(
            "person_name",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.reporting_persons[].name`.",
        ),
        Col::new(
            "no_cik",
            Ty::Boolean,
            true,
            "`Filing.body.beneficial.reporting_persons[].no_cik`: optional bool: NULL when unset. 13D.",
        ),
        Col::new(
            "member_of_group",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.reporting_persons[].member_of_group`. Raw `a` / `b`.",
        ),
        Col::new(
            "fund_type",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.reporting_persons[].fund_type`. = fund_types[0].",
        ),
        Col::new(
            "fund_types",
            Ty::ListUtf8,
            false,
            "`Filing.body.beneficial.reporting_persons[].fund_types[]`: verbatim items in document order; [] when empty. 13D source of funds: WC, PF, AF, BK, SC, OO.",
        ),
        Col::new(
            "citizenship",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.reporting_persons[].citizenship`. EDGAR code.",
        ),
        Col::new(
            "sole_voting_power",
            Ty::Decimal(Family::Q6),
            true,
            "`Filing.body.beneficial.reporting_persons[].sole_voting_power`: decimal s=6 (§4.3, Q6). Shares.",
        ),
        Col::new(
            "shared_voting_power",
            Ty::Decimal(Family::Q6),
            true,
            "`Filing.body.beneficial.reporting_persons[].shared_voting_power`: decimal s=6 (§4.3, Q6). Shares.",
        ),
        Col::new(
            "sole_dispositive_power",
            Ty::Decimal(Family::Q6),
            true,
            "`Filing.body.beneficial.reporting_persons[].sole_dispositive_power`: decimal s=6 (§4.3, Q6). Shares.",
        ),
        Col::new(
            "shared_dispositive_power",
            Ty::Decimal(Family::Q6),
            true,
            "`Filing.body.beneficial.reporting_persons[].shared_dispositive_power`: decimal s=6 (§4.3, Q6). Shares.",
        ),
        Col::new(
            "aggregate_amount_owned",
            Ty::Decimal(Family::Q6),
            true,
            "`Filing.body.beneficial.reporting_persons[].aggregate_amount_owned`: decimal s=6 (§4.3, Q6). Shares.",
        ),
        Col::new(
            "aggregate_excludes_shares",
            Ty::Boolean,
            true,
            "`Filing.body.beneficial.reporting_persons[].aggregate_excludes_shares`: optional bool: NULL when unset.",
        ),
        Col::new(
            "percent_of_class",
            Ty::Decimal(Family::R12),
            true,
            "`Filing.body.beneficial.reporting_persons[].percent_of_class`: decimal s=12 (§4.3, R12). Percent units (7.7 = 7.7%).",
        ),
        Col::new(
            "type_of_reporting_person",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.reporting_persons[].type_of_reporting_person`. = types_of_reporting_person[0].",
        ),
        Col::new(
            "types_of_reporting_person",
            Ty::ListUtf8,
            false,
            "`Filing.body.beneficial.reporting_persons[].types_of_reporting_person[]`: verbatim items in document order; [] when empty. IN, IA, PN, OO, HC, CO, …",
        ),
        Col::new(
            "legal_proceedings",
            Ty::Boolean,
            true,
            "`Filing.body.beneficial.reporting_persons[].legal_proceedings`: optional bool: NULL when unset. 13D.",
        ),
        Col::new(
            "comment",
            Ty::Utf8,
            true,
            "`Filing.body.beneficial.reporting_persons[].comment`.",
        ),
        Col::new(
            "has_parse_issues",
            Ty::Boolean,
            false,
            "Derived: true iff this row wrote ≥1 `parse_issues` row (§4.6).",
        ),
    ],
};
