//! Table specs generated from the final specification §3 (`final-spec.md`).
//! Edit only to fix a divergence from the specification; regenerate
//! `docs/schemas/sec.md` and re-pin the chain schema digests afterwards.

#[allow(unused_imports)]
use super::{Col, Family, Member, TableSpec, Ty};

/// §3.32 `form_d_notices`.
pub(crate) const FORM_D_NOTICES: TableSpec = TableSpec {
    name: super::FORM_D_NOTICES,
    doc: "Form D exempt offerings: primary issuer, offering terms and amounts. Signatures are in `filing_signatures`.",
    filing_context: true,
    cols: &[
        Col::new(
            "schema_version",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.schema_version`.",
        ),
        Col::new(
            "submission_type",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.submission_type`. `D` / `D/A`.",
        ),
        Col::new(
            "previous_accession_number",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.previous_accession_number`. D/A: the filing it amends.",
        ),
        Col::new(
            "issuer_cik",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.primary_issuer.cik`. = filings.cik.",
        ),
        Col::new(
            "issuer_name",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.primary_issuer.entity_name`.",
        ),
        Col::new(
            "issuer_street1",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.primary_issuer.address.street1`.",
        ),
        Col::new(
            "issuer_street2",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.primary_issuer.address.street2`.",
        ),
        Col::new(
            "issuer_city",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.primary_issuer.address.city`.",
        ),
        Col::new(
            "issuer_state",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.primary_issuer.address.state`. EDGAR state/country code.",
        ),
        Col::new(
            "issuer_zip_code",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.primary_issuer.address.zip_code`. Text (keeps leading zeros).",
        ),
        Col::new(
            "issuer_state_description",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.primary_issuer.address.state_description`. Filled only by Forms 3/4/5 and D.",
        ),
        Col::new(
            "issuer_country",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.primary_issuer.address.country`.",
        ),
        Col::new(
            "issuer_non_us_state_territory",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.primary_issuer.address.non_us_state_territory`.",
        ),
        Col::new(
            "issuer_phone",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.primary_issuer.phone`.",
        ),
        Col::new(
            "jurisdiction_of_inc",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.primary_issuer.jurisdiction_of_inc`. `DELAWARE`, …",
        ),
        Col::new(
            "entity_type",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.primary_issuer.entity_type`.",
        ),
        Col::new(
            "entity_type_other_desc",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.primary_issuer.entity_type_other_desc`.",
        ),
        Col::new(
            "year_of_inc",
            Ty::Int32,
            true,
            "`Filing.body.form_d.primary_issuer.year_of_inc`: integer (§4.3), Int32. NULL when incorporated >5 years ago or yet to be formed.",
        ),
        Col::new(
            "year_of_inc_status",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.primary_issuer.year_of_inc_status`. `withinFiveYears`, `overFiveYears`, …",
        ),
        Col::new(
            "issuer_previous_names",
            Ty::ListUtf8,
            false,
            "`Filing.body.form_d.primary_issuer.previous_names[]`: verbatim items in document order; [] when empty.",
        ),
        Col::new(
            "issuer_edgar_previous_names",
            Ty::ListUtf8,
            false,
            "`Filing.body.form_d.primary_issuer.edgar_previous_names[]`: verbatim items in document order; [] when empty.",
        ),
        Col::new(
            "industry_group",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.offering.industry_group`. `Pooled Investment Fund`, `Other Technology`, …",
        ),
        Col::new(
            "investment_fund_type",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.offering.investment_fund_type`. `Hedge Fund`, `Private Equity Fund`, …",
        ),
        Col::new(
            "is_40_act",
            Ty::Boolean,
            true,
            "`Filing.body.form_d.offering.is_40_act`: optional bool: NULL when unset.",
        ),
        Col::new(
            "revenue_range",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.offering.revenue_range`.",
        ),
        Col::new(
            "aggregate_net_asset_value_range",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.offering.aggregate_net_asset_value_range`.",
        ),
        Col::new(
            "offering_is_amendment",
            Ty::Boolean,
            true,
            "`Filing.body.form_d.offering.is_amendment`: proto bool; NULL when `offering` is absent.",
        ),
        Col::new(
            "date_of_first_sale",
            Ty::Date32,
            true,
            "`Filing.body.form_d.offering.date_of_first_sale`: date (§4.2).",
        ),
        Col::new(
            "date_of_first_sale_yet_to_occur",
            Ty::Boolean,
            true,
            "`Filing.body.form_d.offering.date_of_first_sale_yet_to_occur`: optional bool: NULL when unset.",
        ),
        Col::new(
            "more_than_one_year",
            Ty::Boolean,
            true,
            "`Filing.body.form_d.offering.more_than_one_year`: proto bool; NULL when `offering` is absent.",
        ),
        Col::new(
            "is_equity_type",
            Ty::Boolean,
            true,
            "`Filing.body.form_d.offering.is_equity_type`: proto bool; NULL when `offering` is absent.",
        ),
        Col::new(
            "securities_types",
            Ty::ListUtf8,
            false,
            "`Filing.body.form_d.offering.securities_types[]`: verbatim items in document order; [] when empty. `isEquityType`, `isDebtType`, `isPooledInvestmentFundType`, …",
        ),
        Col::new(
            "description_of_other_type",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.offering.description_of_other_type`.",
        ),
        Col::new(
            "is_business_combination",
            Ty::Boolean,
            true,
            "`Filing.body.form_d.offering.is_business_combination`: optional bool: NULL when unset.",
        ),
        Col::new(
            "business_combination_clarification",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.offering.business_combination_clarification`.",
        ),
        Col::new(
            "federal_exemptions",
            Ty::ListUtf8,
            false,
            "`Filing.body.form_d.offering.federal_exemptions[]`: verbatim items in document order; [] when empty. `06b` 506(b), `06c` 506(c), `04` 504, `3C.1`, `3C.7`…",
        ),
        Col::new(
            "minimum_investment",
            Ty::Decimal(Family::M2),
            true,
            "`Filing.body.form_d.offering.minimum_investment`: decimal s=2 (§4.3, M2). USD.",
        ),
        Col::new(
            "total_offering_amount",
            Ty::Decimal(Family::M2),
            true,
            "`Filing.body.form_d.offering.total_offering_amount`: decimal s=2 (§4.3, M2). USD; NULL when `Indefinite`.",
        ),
        Col::new(
            "total_offering_amount_is_indefinite",
            Ty::Boolean,
            false,
            "Derived from `Filing.body.form_d.offering.total_offering_amount`: raw = `Indefinite` (case-insensitive). Removes the \"Indefinite = 0\" footgun.",
        ),
        Col::new(
            "total_amount_sold",
            Ty::Decimal(Family::M2),
            true,
            "`Filing.body.form_d.offering.total_amount_sold`: decimal s=2 (§4.3, M2). USD, cumulative.",
        ),
        Col::new(
            "total_remaining",
            Ty::Decimal(Family::M2),
            true,
            "`Filing.body.form_d.offering.total_remaining`: decimal s=2 (§4.3, M2). USD; NULL when `Indefinite`.",
        ),
        Col::new(
            "total_remaining_is_indefinite",
            Ty::Boolean,
            false,
            "Derived from `Filing.body.form_d.offering.total_remaining`: raw = `Indefinite`.",
        ),
        Col::new(
            "offering_sales_amounts_clarification",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.offering.offering_sales_amounts_clarification`.",
        ),
        Col::new(
            "has_non_accredited_investors",
            Ty::Boolean,
            true,
            "`Filing.body.form_d.offering.has_non_accredited_investors`: proto bool; NULL when `offering` is absent.",
        ),
        Col::new(
            "number_non_accredited_investors",
            Ty::Int64,
            true,
            "`Filing.body.form_d.offering.number_non_accredited_investors`: integer (§4.3), Int64.",
        ),
        Col::new(
            "total_number_already_invested",
            Ty::Int64,
            true,
            "`Filing.body.form_d.offering.total_already_invested`: integer (§4.3), Int64. A COUNT of investors (renamed from `total_already_invested`).",
        ),
        Col::new(
            "sales_commissions",
            Ty::Decimal(Family::M2),
            true,
            "`Filing.body.form_d.offering.sales_commissions`: decimal s=2 (§4.3, M2). USD.",
        ),
        Col::new(
            "sales_commissions_is_estimate",
            Ty::Boolean,
            true,
            "`Filing.body.form_d.offering.sales_commissions_is_estimate`: optional bool: NULL when unset.",
        ),
        Col::new(
            "finders_fees",
            Ty::Decimal(Family::M2),
            true,
            "`Filing.body.form_d.offering.finders_fees`: decimal s=2 (§4.3, M2). USD.",
        ),
        Col::new(
            "finders_fees_is_estimate",
            Ty::Boolean,
            true,
            "`Filing.body.form_d.offering.finders_fees_is_estimate`: optional bool: NULL when unset.",
        ),
        Col::new(
            "sales_commissions_clarification",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.offering.sales_commissions_clarification`.",
        ),
        Col::new(
            "gross_proceeds_used",
            Ty::Decimal(Family::M2),
            true,
            "`Filing.body.form_d.offering.gross_proceeds_used`: decimal s=2 (§4.3, M2). USD paid to related persons.",
        ),
        Col::new(
            "gross_proceeds_used_is_estimate",
            Ty::Boolean,
            true,
            "`Filing.body.form_d.offering.gross_proceeds_used_is_estimate`: optional bool: NULL when unset.",
        ),
        Col::new(
            "use_of_proceeds_clarification",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.offering.use_of_proceeds_clarification`.",
        ),
        Col::new(
            "authorized_representative",
            Ty::Boolean,
            true,
            "`Filing.body.form_d.authorized_representative`: optional bool: NULL when unset.",
        ),
        Col::new(
            "co_issuer_count",
            Ty::UInt32,
            false,
            "Derived from `Filing.body.form_d.issuers[]`: length of the list.",
        ),
        Col::new(
            "related_person_count",
            Ty::UInt32,
            false,
            "Derived from `Filing.body.form_d.related_persons[]`: length of the list.",
        ),
        Col::new(
            "sales_recipient_count",
            Ty::UInt32,
            false,
            "Derived from `Filing.body.form_d.sales_compensation_recipients[]`: length of the list.",
        ),
        Col::new(
            "has_parse_issues",
            Ty::Boolean,
            false,
            "Derived: true iff this row wrote ≥1 `parse_issues` row (§4.6).",
        ),
    ],
};

/// §3.33 `form_d_co_issuers`.
pub(crate) const FORM_D_CO_ISSUERS: TableSpec = TableSpec {
    name: super::FORM_D_CO_ISSUERS,
    doc: "Co-issuers of a Form D.",
    filing_context: true,
    cols: &[
        Col::new(
            "issuer_cik",
            Ty::Utf8,
            true,
            "Copy of `form_d_notices.issuer_cik`. The primary issuer.",
        ),
        Col::new(
            "co_issuer_index",
            Ty::UInt32,
            false,
            "Derived: position in `issuers`.",
        ),
        Col::new(
            "co_issuer_cik",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.issuers[].cik`.",
        ),
        Col::new(
            "co_issuer_name",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.issuers[].entity_name`.",
        ),
        Col::new(
            "co_issuer_street1",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.issuers[].address.street1`.",
        ),
        Col::new(
            "co_issuer_street2",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.issuers[].address.street2`.",
        ),
        Col::new(
            "co_issuer_city",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.issuers[].address.city`.",
        ),
        Col::new(
            "co_issuer_state",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.issuers[].address.state`. EDGAR state/country code.",
        ),
        Col::new(
            "co_issuer_zip_code",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.issuers[].address.zip_code`. Text (keeps leading zeros).",
        ),
        Col::new(
            "co_issuer_state_description",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.issuers[].address.state_description`. Filled only by Forms 3/4/5 and D.",
        ),
        Col::new(
            "co_issuer_country",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.issuers[].address.country`.",
        ),
        Col::new(
            "co_issuer_non_us_state_territory",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.issuers[].address.non_us_state_territory`.",
        ),
        Col::new(
            "co_issuer_phone",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.issuers[].phone`.",
        ),
        Col::new(
            "jurisdiction_of_inc",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.issuers[].jurisdiction_of_inc`.",
        ),
        Col::new(
            "entity_type",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.issuers[].entity_type`.",
        ),
        Col::new(
            "entity_type_other_desc",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.issuers[].entity_type_other_desc`.",
        ),
        Col::new(
            "year_of_inc",
            Ty::Int32,
            true,
            "`Filing.body.form_d.issuers[].year_of_inc`: integer (§4.3), Int32.",
        ),
        Col::new(
            "year_of_inc_status",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.issuers[].year_of_inc_status`.",
        ),
        Col::new(
            "previous_names",
            Ty::ListUtf8,
            false,
            "`Filing.body.form_d.issuers[].previous_names[]`: verbatim items in document order; [] when empty.",
        ),
        Col::new(
            "edgar_previous_names",
            Ty::ListUtf8,
            false,
            "`Filing.body.form_d.issuers[].edgar_previous_names[]`: verbatim items in document order; [] when empty.",
        ),
        Col::new(
            "has_parse_issues",
            Ty::Boolean,
            false,
            "Derived: true iff this row wrote ≥1 `parse_issues` row (§4.6).",
        ),
    ],
};

/// §3.34 `form_d_related_persons`.
pub(crate) const FORM_D_RELATED_PERSONS: TableSpec = TableSpec {
    name: super::FORM_D_RELATED_PERSONS,
    doc: "People related to a Form D issuer.",
    filing_context: true,
    cols: &[
        Col::new(
            "issuer_cik",
            Ty::Utf8,
            true,
            "Copy of `form_d_notices.issuer_cik`.",
        ),
        Col::new(
            "person_index",
            Ty::UInt32,
            false,
            "Derived: position in `related_persons`.",
        ),
        Col::new(
            "first_name",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.related_persons[].first_name`. `N/A` for entities.",
        ),
        Col::new(
            "middle_name",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.related_persons[].middle_name`.",
        ),
        Col::new(
            "last_name",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.related_persons[].last_name`.",
        ),
        Col::new(
            "person_street1",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.related_persons[].address.street1`.",
        ),
        Col::new(
            "person_street2",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.related_persons[].address.street2`.",
        ),
        Col::new(
            "person_city",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.related_persons[].address.city`.",
        ),
        Col::new(
            "person_state",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.related_persons[].address.state`. EDGAR state/country code.",
        ),
        Col::new(
            "person_zip_code",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.related_persons[].address.zip_code`. Text (keeps leading zeros).",
        ),
        Col::new(
            "person_state_description",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.related_persons[].address.state_description`. Filled only by Forms 3/4/5 and D.",
        ),
        Col::new(
            "person_country",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.related_persons[].address.country`.",
        ),
        Col::new(
            "person_non_us_state_territory",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.related_persons[].address.non_us_state_territory`.",
        ),
        Col::new(
            "relationships",
            Ty::ListUtf8,
            false,
            "`Filing.body.form_d.related_persons[].relationships[]`: verbatim items in document order; [] when empty. `Executive Officer`, `Director`, `Promoter`.",
        ),
        Col::new(
            "relationship_clarification",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.related_persons[].relationship_clarification`.",
        ),
    ],
};

/// §3.35 `form_d_sales_recipients`.
pub(crate) const FORM_D_SALES_RECIPIENTS: TableSpec = TableSpec {
    name: super::FORM_D_SALES_RECIPIENTS,
    doc: "Placement agents and brokers paid on a Form D offering.",
    filing_context: true,
    cols: &[
        Col::new(
            "issuer_cik",
            Ty::Utf8,
            true,
            "Copy of `form_d_notices.issuer_cik`.",
        ),
        Col::new(
            "recipient_index",
            Ty::UInt32,
            false,
            "Derived: position in `sales_compensation_recipients`.",
        ),
        Col::new(
            "recipient_name",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.sales_compensation_recipients[].name`.",
        ),
        Col::new(
            "recipient_crd_number",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.sales_compensation_recipients[].crd_number`. Raw (`None` allowed).",
        ),
        Col::new(
            "associated_bd_name",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.sales_compensation_recipients[].associated_bd_name`.",
        ),
        Col::new(
            "associated_bd_crd_number",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.sales_compensation_recipients[].associated_bd_crd_number`.",
        ),
        Col::new(
            "recipient_street1",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.sales_compensation_recipients[].address.street1`.",
        ),
        Col::new(
            "recipient_street2",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.sales_compensation_recipients[].address.street2`.",
        ),
        Col::new(
            "recipient_city",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.sales_compensation_recipients[].address.city`.",
        ),
        Col::new(
            "recipient_state",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.sales_compensation_recipients[].address.state`. EDGAR state/country code.",
        ),
        Col::new(
            "recipient_zip_code",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.sales_compensation_recipients[].address.zip_code`. Text (keeps leading zeros).",
        ),
        Col::new(
            "recipient_state_description",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.sales_compensation_recipients[].address.state_description`. Filled only by Forms 3/4/5 and D.",
        ),
        Col::new(
            "recipient_country",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.sales_compensation_recipients[].address.country`.",
        ),
        Col::new(
            "recipient_non_us_state_territory",
            Ty::Utf8,
            true,
            "`Filing.body.form_d.sales_compensation_recipients[].address.non_us_state_territory`.",
        ),
        Col::new(
            "states_of_solicitation",
            Ty::ListUtf8,
            false,
            "`Filing.body.form_d.sales_compensation_recipients[].states_of_solicitation[]`: verbatim items in document order; [] when empty. State codes or `All States`.",
        ),
        Col::new(
            "foreign_solicitation",
            Ty::Boolean,
            true,
            "`Filing.body.form_d.sales_compensation_recipients[].foreign_solicitation`: optional bool: NULL when unset.",
        ),
    ],
};
