//! Table specs generated from the final specification §3 (`final-spec.md`).
//! Edit only to fix a divergence from the specification; regenerate
//! `docs/schemas/sec.md` and re-pin the chain schema digests afterwards.

#[allow(unused_imports)]
use super::{Col, Family, Member, TableSpec, Ty};

/// §3.41 `form_c_notices`.
pub(crate) const FORM_C_NOTICES: TableSpec = TableSpec {
    name: super::FORM_C_NOTICES,
    doc: "Regulation Crowdfunding filings: issuer, portal, offering terms and financials. Signatures are in `filing_signatures`.",
    filing_context: true,
    cols: &[
        Col::new(
            "filer_cik",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.filer_cik`. The issuer.",
        ),
        Col::new(
            "issuer_name",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.issuer.name`.",
        ),
        Col::new(
            "issuer_legal_status_form",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.issuer.legal_status_form`.",
        ),
        Col::new(
            "issuer_legal_status_other_desc",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.issuer.legal_status_other_desc`.",
        ),
        Col::new(
            "issuer_jurisdiction",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.issuer.jurisdiction`.",
        ),
        Col::new(
            "issuer_date_incorporation",
            Ty::Date32,
            true,
            "`Filing.body.form_c.issuer.date_incorporation`: date (§4.2).",
        ),
        Col::new(
            "issuer_street1",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.issuer.address.street1`.",
        ),
        Col::new(
            "issuer_street2",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.issuer.address.street2`.",
        ),
        Col::new(
            "issuer_city",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.issuer.address.city`.",
        ),
        Col::new(
            "issuer_state",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.issuer.address.state`. EDGAR state/country code.",
        ),
        Col::new(
            "issuer_zip_code",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.issuer.address.zip_code`. Text (keeps leading zeros).",
        ),
        Col::new(
            "issuer_state_description",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.issuer.address.state_description`. Filled only by Forms 3/4/5 and D.",
        ),
        Col::new(
            "issuer_country",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.issuer.address.country`.",
        ),
        Col::new(
            "issuer_non_us_state_territory",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.issuer.address.non_us_state_territory`.",
        ),
        Col::new(
            "issuer_website",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.issuer.website`.",
        ),
        Col::new(
            "intermediary_company_name",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.intermediary_company_name`. Funding portal / broker.",
        ),
        Col::new(
            "intermediary_cik",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.intermediary_cik`.",
        ),
        Col::new(
            "intermediary_file_number",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.intermediary_file_number`. `007-`/`008-`.",
        ),
        Col::new(
            "intermediary_crd_number",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.intermediary_crd_number`.",
        ),
        Col::new(
            "issuer_info_is_amendment",
            Ty::Boolean,
            true,
            "`Filing.body.form_c.is_amendment`: optional bool: NULL when unset.",
        ),
        Col::new(
            "nature_of_amendment",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.nature_of_amendment`.",
        ),
        Col::new(
            "progress_update",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.progress_update`. C-U.",
        ),
        Col::new(
            "is_co_issuer",
            Ty::Boolean,
            true,
            "`Filing.body.form_c.is_co_issuer`: optional bool: NULL when unset.",
        ),
        Col::new(
            "period",
            Ty::Date32,
            true,
            "`Filing.body.form_c.period`: date (§4.2). C-AR fiscal period end.",
        ),
        Col::new(
            "security_type",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.offering.security_type`.",
        ),
        Col::new(
            "security_offered_other_desc",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.offering.security_offered_other_desc`. E.g. `SAFE`.",
        ),
        Col::new(
            "num_securities_offered",
            Ty::Decimal(Family::Q6),
            true,
            "`Filing.body.form_c.offering.num_securities_offered`: decimal s=6 (§4.3, Q6).",
        ),
        Col::new(
            "price",
            Ty::Decimal(Family::Q6),
            true,
            "`Filing.body.form_c.offering.price`: decimal s=6 (§4.3, Q6). USD per security.",
        ),
        Col::new(
            "price_determination_method",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.offering.price_determination_method`.",
        ),
        Col::new(
            "offering_amount",
            Ty::Decimal(Family::M2),
            true,
            "`Filing.body.form_c.offering.offering_amount`: decimal s=2 (§4.3, M2). TARGET raise, USD.",
        ),
        Col::new(
            "maximum_offering_amount",
            Ty::Decimal(Family::M2),
            true,
            "`Filing.body.form_c.offering.maximum_offering_amount`: decimal s=2 (§4.3, M2). Cap if oversubscribed, USD.",
        ),
        Col::new(
            "over_subscription_accepted",
            Ty::Boolean,
            true,
            "`Filing.body.form_c.offering.over_subscription_accepted`: proto bool; NULL when `offering` is absent.",
        ),
        Col::new(
            "over_subscription_allocation_type",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.offering.over_subscription_allocation_type`.",
        ),
        Col::new(
            "desc_over_subscription",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.offering.desc_over_subscription`.",
        ),
        Col::new(
            "deadline_date",
            Ty::Date32,
            true,
            "`Filing.body.form_c.offering.deadline_date`: date (§4.2).",
        ),
        Col::new(
            "compensation_amount",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.offering.compensation_amount`. FREE TEXT, not a number.",
        ),
        Col::new(
            "financial_interest",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.offering.financial_interest`.",
        ),
        Col::new(
            "offering_jurisdictions",
            Ty::ListUtf8,
            false,
            "`Filing.body.form_c.offering_jurisdictions[]`: verbatim items in document order; [] when empty.",
        ),
        Col::new(
            "has_financials",
            Ty::Boolean,
            false,
            "Derived from `Filing.body.form_c.financials`: `financials` present.",
        ),
        Col::new(
            "current_employees",
            Ty::Int64,
            true,
            "`Filing.body.form_c.financials.current_employees`: integer (§4.3), Int64. Count.",
        ),
        Col::new(
            "total_assets_most_recent_fy",
            Ty::Decimal(Family::M2),
            true,
            "`Filing.body.form_c.financials.total_assets_most_recent_fy`: decimal s=2 (§4.3, M2). USD.",
        ),
        Col::new(
            "total_assets_prior_fy",
            Ty::Decimal(Family::M2),
            true,
            "`Filing.body.form_c.financials.total_assets_prior_fy`: decimal s=2 (§4.3, M2). USD.",
        ),
        Col::new(
            "cash_equivalents_most_recent_fy",
            Ty::Decimal(Family::M2),
            true,
            "`Filing.body.form_c.financials.cash_equivalents_most_recent_fy`: decimal s=2 (§4.3, M2). USD.",
        ),
        Col::new(
            "cash_equivalents_prior_fy",
            Ty::Decimal(Family::M2),
            true,
            "`Filing.body.form_c.financials.cash_equivalents_prior_fy`: decimal s=2 (§4.3, M2). USD.",
        ),
        Col::new(
            "accounts_receivable_most_recent_fy",
            Ty::Decimal(Family::M2),
            true,
            "`Filing.body.form_c.financials.accounts_receivable_most_recent_fy`: decimal s=2 (§4.3, M2). USD.",
        ),
        Col::new(
            "accounts_receivable_prior_fy",
            Ty::Decimal(Family::M2),
            true,
            "`Filing.body.form_c.financials.accounts_receivable_prior_fy`: decimal s=2 (§4.3, M2). USD.",
        ),
        Col::new(
            "short_term_debt_most_recent_fy",
            Ty::Decimal(Family::M2),
            true,
            "`Filing.body.form_c.financials.short_term_debt_most_recent_fy`: decimal s=2 (§4.3, M2). USD.",
        ),
        Col::new(
            "short_term_debt_prior_fy",
            Ty::Decimal(Family::M2),
            true,
            "`Filing.body.form_c.financials.short_term_debt_prior_fy`: decimal s=2 (§4.3, M2). USD.",
        ),
        Col::new(
            "long_term_debt_most_recent_fy",
            Ty::Decimal(Family::M2),
            true,
            "`Filing.body.form_c.financials.long_term_debt_most_recent_fy`: decimal s=2 (§4.3, M2). USD.",
        ),
        Col::new(
            "long_term_debt_prior_fy",
            Ty::Decimal(Family::M2),
            true,
            "`Filing.body.form_c.financials.long_term_debt_prior_fy`: decimal s=2 (§4.3, M2). USD.",
        ),
        Col::new(
            "revenue_most_recent_fy",
            Ty::Decimal(Family::M2),
            true,
            "`Filing.body.form_c.financials.revenue_most_recent_fy`: decimal s=2 (§4.3, M2). USD.",
        ),
        Col::new(
            "revenue_prior_fy",
            Ty::Decimal(Family::M2),
            true,
            "`Filing.body.form_c.financials.revenue_prior_fy`: decimal s=2 (§4.3, M2). USD.",
        ),
        Col::new(
            "cost_goods_sold_most_recent_fy",
            Ty::Decimal(Family::M2),
            true,
            "`Filing.body.form_c.financials.cost_goods_sold_most_recent_fy`: decimal s=2 (§4.3, M2). USD.",
        ),
        Col::new(
            "cost_goods_sold_prior_fy",
            Ty::Decimal(Family::M2),
            true,
            "`Filing.body.form_c.financials.cost_goods_sold_prior_fy`: decimal s=2 (§4.3, M2). USD.",
        ),
        Col::new(
            "tax_paid_most_recent_fy",
            Ty::Decimal(Family::M2),
            true,
            "`Filing.body.form_c.financials.tax_paid_most_recent_fy`: decimal s=2 (§4.3, M2). USD.",
        ),
        Col::new(
            "tax_paid_prior_fy",
            Ty::Decimal(Family::M2),
            true,
            "`Filing.body.form_c.financials.tax_paid_prior_fy`: decimal s=2 (§4.3, M2). USD.",
        ),
        Col::new(
            "net_income_most_recent_fy",
            Ty::Decimal(Family::M2),
            true,
            "`Filing.body.form_c.financials.net_income_most_recent_fy`: decimal s=2 (§4.3, M2). USD.",
        ),
        Col::new(
            "net_income_prior_fy",
            Ty::Decimal(Family::M2),
            true,
            "`Filing.body.form_c.financials.net_income_prior_fy`: decimal s=2 (§4.3, M2). USD.",
        ),
        Col::new(
            "co_issuer_count",
            Ty::UInt32,
            false,
            "Derived from `Filing.body.form_c.co_issuers[]`: length of the list.",
        ),
        Col::new(
            "has_parse_issues",
            Ty::Boolean,
            false,
            "Derived: true iff this row wrote ≥1 `parse_issues` row (§4.6).",
        ),
    ],
};

/// §3.42 `form_c_co_issuers`.
pub(crate) const FORM_C_CO_ISSUERS: TableSpec = TableSpec {
    name: super::FORM_C_CO_ISSUERS,
    doc: "Co-issuers (e.g. crowdfunding SPVs) of a Form C.",
    filing_context: true,
    cols: &[
        Col::new(
            "filer_cik",
            Ty::Utf8,
            true,
            "Copy of `form_c_notices.filer_cik`. The primary issuer (like `form_d_co_issuers.issuer_cik`).",
        ),
        Col::new(
            "co_issuer_index",
            Ty::UInt32,
            false,
            "Derived: position in `co_issuers`.",
        ),
        Col::new(
            "co_issuer_name",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.co_issuers[].name`.",
        ),
        Col::new(
            "legal_status_form",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.co_issuers[].legal_status_form`.",
        ),
        Col::new(
            "legal_status_other_desc",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.co_issuers[].legal_status_other_desc`.",
        ),
        Col::new(
            "jurisdiction",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.co_issuers[].jurisdiction`.",
        ),
        Col::new(
            "date_incorporation",
            Ty::Date32,
            true,
            "`Filing.body.form_c.co_issuers[].date_incorporation`: date (§4.2).",
        ),
        Col::new(
            "co_issuer_street1",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.co_issuers[].address.street1`.",
        ),
        Col::new(
            "co_issuer_street2",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.co_issuers[].address.street2`.",
        ),
        Col::new(
            "co_issuer_city",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.co_issuers[].address.city`.",
        ),
        Col::new(
            "co_issuer_state",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.co_issuers[].address.state`. EDGAR state/country code.",
        ),
        Col::new(
            "co_issuer_zip_code",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.co_issuers[].address.zip_code`. Text (keeps leading zeros).",
        ),
        Col::new(
            "co_issuer_state_description",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.co_issuers[].address.state_description`. Filled only by Forms 3/4/5 and D.",
        ),
        Col::new(
            "co_issuer_country",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.co_issuers[].address.country`.",
        ),
        Col::new(
            "co_issuer_non_us_state_territory",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.co_issuers[].address.non_us_state_territory`.",
        ),
        Col::new(
            "website",
            Ty::Utf8,
            true,
            "`Filing.body.form_c.co_issuers[].website`.",
        ),
        Col::new(
            "has_parse_issues",
            Ty::Boolean,
            false,
            "Derived: true iff this row wrote ≥1 `parse_issues` row (§4.6).",
        ),
    ],
};
