//! Table specs generated from the final specification §3 (`final-spec.md`).
//! Edit only to fix a divergence from the specification; regenerate
//! `docs/schemas/sec.md` and re-pin the chain schema digests afterwards.

#[allow(unused_imports)]
use super::{Col, Family, Member, TableSpec, Ty};

/// §3.23 `nport_reports`.
pub(crate) const NPORT_REPORTS: TableSpec = TableSpec {
    name: super::NPORT_REPORTS,
    doc: "N-PORT fund header: registrant, series, as-of date and fund totals. The signature is in `filing_signatures`.",
    filing_context: true,
    cols: &[
        Col::new(
            "filer_cik",
            Ty::Utf8,
            true,
            "`Filing.body.nport.filer_cik`. Registrant.",
        ),
        Col::new(
            "registrant_name",
            Ty::Utf8,
            true,
            "`Filing.body.nport.general_info.reg_name`.",
        ),
        Col::new(
            "registrant_file_number",
            Ty::Utf8,
            true,
            "`Filing.body.nport.general_info.reg_file_number`. `811-…`.",
        ),
        Col::new(
            "registrant_cik",
            Ty::Utf8,
            true,
            "`Filing.body.nport.general_info.reg_cik`.",
        ),
        Col::new(
            "registrant_lei",
            Ty::Utf8,
            true,
            "`Filing.body.nport.general_info.reg_lei`.",
        ),
        Col::new(
            "registrant_street1",
            Ty::Utf8,
            true,
            "`Filing.body.nport.general_info.reg_address.street1`.",
        ),
        Col::new(
            "registrant_street2",
            Ty::Utf8,
            true,
            "`Filing.body.nport.general_info.reg_address.street2`.",
        ),
        Col::new(
            "registrant_city",
            Ty::Utf8,
            true,
            "`Filing.body.nport.general_info.reg_address.city`.",
        ),
        Col::new(
            "registrant_state",
            Ty::Utf8,
            true,
            "`Filing.body.nport.general_info.reg_address.state`. ISO 3166-2 (`US-MA`), unlike EDGAR codes elsewhere.",
        ),
        Col::new(
            "registrant_zip_code",
            Ty::Utf8,
            true,
            "`Filing.body.nport.general_info.reg_address.zip_code`. Text (keeps leading zeros).",
        ),
        Col::new(
            "registrant_state_description",
            Ty::Utf8,
            true,
            "`Filing.body.nport.general_info.reg_address.state_description`. Filled only by Forms 3/4/5 and D.",
        ),
        Col::new(
            "registrant_country",
            Ty::Utf8,
            true,
            "`Filing.body.nport.general_info.reg_address.country`.",
        ),
        Col::new(
            "registrant_non_us_state_territory",
            Ty::Utf8,
            true,
            "`Filing.body.nport.general_info.reg_address.non_us_state_territory`.",
        ),
        Col::new(
            "registrant_phone",
            Ty::Utf8,
            true,
            "`Filing.body.nport.general_info.reg_phone`.",
        ),
        Col::new(
            "series_name",
            Ty::Utf8,
            true,
            "`Filing.body.nport.general_info.series_name`.",
        ),
        Col::new(
            "series_id",
            Ty::Utf8,
            true,
            "`Filing.body.nport.general_info.series_id`. `S000…`; NULL on ~9%.",
        ),
        Col::new(
            "series_lei",
            Ty::Utf8,
            true,
            "`Filing.body.nport.general_info.series_lei`. `N/A` common.",
        ),
        Col::new(
            "fiscal_year_end",
            Ty::Date32,
            true,
            "`Filing.body.nport.general_info.rep_period_end`: date (§4.2). Proto `rep_period_end` (repPdEnd) is the FISCAL YEAR END: renamed.",
        ),
        Col::new(
            "as_of_date",
            Ty::Date32,
            true,
            "`Filing.body.nport.general_info.rep_period_date`: date (§4.2). Proto `rep_period_date` (repPdDate): the holdings as-of date.",
        ),
        Col::new(
            "is_final_filing",
            Ty::Boolean,
            true,
            "`Filing.body.nport.general_info.is_final_filing`: proto bool; NULL when `general_info` is absent.",
        ),
        Col::new(
            "total_assets",
            Ty::Decimal(Family::N10),
            true,
            "`Filing.body.nport.fund_info.total_assets`: decimal s=10 (§4.3, N10). USD.",
        ),
        Col::new(
            "total_liabilities",
            Ty::Decimal(Family::N10),
            true,
            "`Filing.body.nport.fund_info.total_liabilities`: decimal s=10 (§4.3, N10). USD.",
        ),
        Col::new(
            "net_assets",
            Ty::Decimal(Family::N10),
            true,
            "`Filing.body.nport.fund_info.net_assets`: decimal s=10 (§4.3, N10). USD (fund AUM).",
        ),
        Col::new(
            "assets_invested",
            Ty::Decimal(Family::N10),
            true,
            "`Filing.body.nport.fund_info.assets_invested`: decimal s=10 (§4.3, N10). USD.",
        ),
        Col::new(
            "misc_securities_assets",
            Ty::Decimal(Family::N10),
            true,
            "`Filing.body.nport.fund_info.misc_securities_assets`: decimal s=10 (§4.3, N10). USD.",
        ),
        Col::new(
            "cash_not_reported",
            Ty::Decimal(Family::N10),
            true,
            "`Filing.body.nport.fund_info.cash_not_reported`: decimal s=10 (§4.3, N10). USD.",
        ),
        Col::new(
            "explanatory_notes",
            Ty::ListStruct(&[("note_item", Member::Utf8), ("note", Member::Utf8)]),
            false,
            "`Filing.body.nport.explanatory_notes[]`: one struct per element {note_item ← .note_item, note ← .note}, verbatim ('' → NULL); [] when empty. Part E notes, e.g. item `B.5.a`.",
        ),
        Col::new(
            "holdings_count",
            Ty::UInt32,
            false,
            "Derived from `Filing.body.nport.holdings[]`: length of the list. Named like `form13f_reports.holdings_count`.",
        ),
        Col::new(
            "derivative_holding_count",
            Ty::UInt32,
            false,
            "Derived from `Filing.body.nport.holdings[].derivative`: holdings with `derivative` set.",
        ),
        Col::new(
            "debt_holding_count",
            Ty::UInt32,
            false,
            "Derived from `Filing.body.nport.holdings[].debt_security`: holdings with `debt_security` set.",
        ),
        Col::new(
            "monthly_return_class_count",
            Ty::UInt32,
            false,
            "Derived from `Filing.body.nport.fund_info.monthly_total_returns[]`: length of the list.",
        ),
        Col::new(
            "has_parse_issues",
            Ty::Boolean,
            false,
            "Derived: true iff this row wrote ≥1 `parse_issues` row (§4.6).",
        ),
    ],
};

/// §3.24 `nport_monthly_returns`.
pub(crate) const NPORT_MONTHLY_RETURNS: TableSpec = TableSpec {
    name: super::NPORT_MONTHLY_RETURNS,
    doc: "Monthly total returns per share class, with the month-end each return belongs to.",
    filing_context: true,
    cols: &[
        Col::new(
            "series_id",
            Ty::Utf8,
            true,
            "Copy of `nport_reports.series_id`.",
        ),
        Col::new(
            "as_of_date",
            Ty::Date32,
            true,
            "Copy of `nport_reports.as_of_date`.",
        ),
        Col::new(
            "return_index",
            Ty::UInt32,
            false,
            "Derived: position in `monthly_total_returns`.",
        ),
        Col::new(
            "class_id",
            Ty::Utf8,
            true,
            "`Filing.body.nport.fund_info.monthly_total_returns[].class_id`. `C000…` (placeholders `C000000000`).",
        ),
        Col::new(
            "return_month1",
            Ty::Decimal(Family::R12),
            true,
            "`Filing.body.nport.fund_info.monthly_total_returns[].return_month1`: decimal s=12 (§4.3, R12). Percent; first month of the quarter.",
        ),
        Col::new(
            "return_month2",
            Ty::Decimal(Family::R12),
            true,
            "`Filing.body.nport.fund_info.monthly_total_returns[].return_month2`: decimal s=12 (§4.3, R12). Percent.",
        ),
        Col::new(
            "return_month3",
            Ty::Decimal(Family::R12),
            true,
            "`Filing.body.nport.fund_info.monthly_total_returns[].return_month3`: decimal s=12 (§4.3, R12). Percent; the as-of month.",
        ),
        Col::new(
            "month1_end",
            Ty::Date32,
            true,
            "Derived from `as_of_date`: last day of the month two months before `as_of_date`.",
        ),
        Col::new(
            "month2_end",
            Ty::Date32,
            true,
            "Derived from `as_of_date`: last day of the month before `as_of_date`.",
        ),
        Col::new(
            "month3_end",
            Ty::Date32,
            true,
            "Derived from `as_of_date`: last day of `as_of_date`'s month.",
        ),
        Col::new(
            "has_parse_issues",
            Ty::Boolean,
            false,
            "Derived: true iff this row wrote ≥1 `parse_issues` row (§4.6).",
        ),
    ],
};

/// §3.25 `nport_monthly_activity`.
pub(crate) const NPORT_MONTHLY_ACTIVITY: TableSpec = TableSpec {
    name: super::NPORT_MONTHLY_ACTIVITY,
    doc: "Monthly sales, reinvestments, redemptions and gains of a fund.",
    filing_context: true,
    cols: &[
        Col::new(
            "series_id",
            Ty::Utf8,
            true,
            "Copy of `nport_reports.series_id`.",
        ),
        Col::new(
            "as_of_date",
            Ty::Date32,
            true,
            "Copy of `nport_reports.as_of_date`.",
        ),
        Col::new(
            "activity_index",
            Ty::UInt32,
            false,
            "Derived: position in `monthly_activity`.",
        ),
        Col::new(
            "month",
            Ty::UInt32,
            false,
            "`Filing.body.nport.fund_info.monthly_activity[].month`: proto uint32. 1, 2 or 3 (N in `monNFlow`).",
        ),
        Col::new(
            "month_end",
            Ty::Date32,
            true,
            "Derived from `month, as_of_date`: last day of the month `3 − month` months before `as_of_date`'s month; NULL when `month` ∉ {1, 2, 3} (proto3 `0` = unset) or `as_of_date` is NULL. Months 1..3 only on the samples.",
        ),
        Col::new(
            "sales",
            Ty::Decimal(Family::N10),
            true,
            "`Filing.body.nport.fund_info.monthly_activity[].sales`: decimal s=10 (§4.3, N10). USD.",
        ),
        Col::new(
            "reinvestment",
            Ty::Decimal(Family::N10),
            true,
            "`Filing.body.nport.fund_info.monthly_activity[].reinvestment`: decimal s=10 (§4.3, N10). USD.",
        ),
        Col::new(
            "redemption",
            Ty::Decimal(Family::N10),
            true,
            "`Filing.body.nport.fund_info.monthly_activity[].redemption`: decimal s=10 (§4.3, N10). USD.",
        ),
        Col::new(
            "net_realized_gain",
            Ty::Decimal(Family::N10),
            true,
            "`Filing.body.nport.fund_info.monthly_activity[].net_realized_gain`: decimal s=10 (§4.3, N10). USD.",
        ),
        Col::new(
            "net_unrealized_appreciation",
            Ty::Decimal(Family::N10),
            true,
            "`Filing.body.nport.fund_info.monthly_activity[].net_unrealized_appreciation`: decimal s=10 (§4.3, N10). USD.",
        ),
        Col::new(
            "has_parse_issues",
            Ty::Boolean,
            false,
            "Derived: true iff this row wrote ≥1 `parse_issues` row (§4.6).",
        ),
    ],
};

/// §3.26 `nport_holdings`.
pub(crate) const NPORT_HOLDINGS: TableSpec = TableSpec {
    name: super::NPORT_HOLDINGS,
    doc: "Fund positions with identifiers, value, debt terms and securities lending; derivative terms are in `nport_derivatives`.",
    filing_context: true,
    cols: &[
        Col::new(
            "registrant_name",
            Ty::Utf8,
            true,
            "Copy of `nport_reports.registrant_name`.",
        ),
        Col::new(
            "series_id",
            Ty::Utf8,
            true,
            "Copy of `nport_reports.series_id`.",
        ),
        Col::new(
            "series_name",
            Ty::Utf8,
            true,
            "Copy of `nport_reports.series_name`.",
        ),
        Col::new(
            "as_of_date",
            Ty::Date32,
            true,
            "Copy of `nport_reports.as_of_date`.",
        ),
        Col::new(
            "holding_index",
            Ty::UInt32,
            false,
            "Derived: position in `holdings`.",
        ),
        Col::new(
            "issuer_name",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].name`. Proto `name`.",
        ),
        Col::new(
            "issuer_lei",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].lei`. `N/A` on ~32%.",
        ),
        Col::new(
            "issuer_lei_norm",
            Ty::Utf8,
            true,
            "Derived from `Filing.body.nport.holdings[].lei`: §4.4 `lei_norm`.",
        ),
        Col::new(
            "issue_title",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].title`. Proto `title`.",
        ),
        Col::new(
            "cusip",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].cusip`. Placeholders `000000000`, `N/A`, `999999999`.",
        ),
        Col::new(
            "cusip_norm",
            Ty::Utf8,
            true,
            "Derived from `Filing.body.nport.holdings[].cusip`: §4.4 `cusip_norm`.",
        ),
        Col::new(
            "isin",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].isin`. Best identifier (~87%).",
        ),
        Col::new(
            "ticker",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].ticker`. ~13% present; junk such as `USD`.",
        ),
        Col::new(
            "other_identifier",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].other_identifier`. = other_identifiers[0].value.",
        ),
        Col::new(
            "other_identifiers",
            Ty::ListStruct(&[("description", Member::Utf8), ("value", Member::Utf8)]),
            false,
            "`Filing.body.nport.holdings[].other_identifiers[]`: one struct per element {description ← .description, value ← .value}, verbatim ('' → NULL); [] when empty. SEDOL, internal ids, …",
        ),
        Col::new(
            "balance",
            Ty::Decimal(Family::N10),
            true,
            "`Filing.body.nport.holdings[].balance`: decimal s=10 (§4.3, N10). Quantity in `units`.",
        ),
        Col::new(
            "units",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].units`. `NS` shares, `PA` principal, `NC` contracts, `OU` other.",
        ),
        Col::new(
            "units_description",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].units_description`. Units `OU`.",
        ),
        Col::new(
            "currency",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].currency`. ISO 4217.",
        ),
        Col::new(
            "exchange_rate",
            Ty::Decimal(Family::R12),
            true,
            "`Filing.body.nport.holdings[].exchange_rate`: decimal s=12 (§4.3, R12). Non-USD holdings.",
        ),
        Col::new(
            "value_usd",
            Ty::Decimal(Family::N10),
            true,
            "`Filing.body.nport.holdings[].value_usd`: decimal s=10 (§4.3, N10). Fair value, USD.",
        ),
        Col::new(
            "pct_value",
            Ty::Decimal(Family::R12),
            true,
            "`Filing.body.nport.holdings[].pct_value`: decimal s=12 (§4.3, R12). PERCENT of net assets (2.33 = 2.33%); negative for shorts.",
        ),
        Col::new(
            "payoff_profile",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].payoff_profile`. `Long` / `Short` / `N/A`.",
        ),
        Col::new(
            "asset_category",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].asset_category`. `EC`, `DBT`, `ABS-MBS`, …",
        ),
        Col::new(
            "asset_category_description",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].asset_category_description`. Asset_category `OTHER`.",
        ),
        Col::new(
            "issuer_category",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].issuer_category`. `CORP`, `UST`, `MUN`, …",
        ),
        Col::new(
            "issuer_category_description",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].issuer_category_description`.",
        ),
        Col::new(
            "investment_country",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].investment_country`. ISO 3166-1 alpha-2.",
        ),
        Col::new(
            "fair_value_level",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].fair_value_level`. Code `1`/`2`/`3`/`N/A`: kept as text.",
        ),
        Col::new(
            "is_restricted",
            Ty::Boolean,
            false,
            "`Filing.body.nport.holdings[].is_restricted`: proto bool (false = false or absent).",
        ),
        Col::new(
            "has_debt_security",
            Ty::Boolean,
            false,
            "Derived from `Filing.body.nport.holdings[].debt_security`: `debt_security` present.",
        ),
        Col::new(
            "debt_maturity_date",
            Ty::Date32,
            true,
            "`Filing.body.nport.holdings[].debt_security.maturity_date`: date (§4.2). `9999-12-31` placeholders kept.",
        ),
        Col::new(
            "debt_coupon_kind",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].debt_security.coupon_kind`. `Fixed`/`Floating`/`Variable`/`None`.",
        ),
        Col::new(
            "debt_annualized_rate",
            Ty::Decimal(Family::R12),
            true,
            "`Filing.body.nport.holdings[].debt_security.annualized_rate`: decimal s=12 (§4.3, R12). Percent.",
        ),
        Col::new(
            "debt_is_default",
            Ty::Boolean,
            true,
            "`Filing.body.nport.holdings[].debt_security.is_default`: optional bool: NULL when unset.",
        ),
        Col::new(
            "debt_are_interest_payments_in_arrears",
            Ty::Boolean,
            true,
            "`Filing.body.nport.holdings[].debt_security.are_interest_payments_in_arrears`: optional bool: NULL when unset.",
        ),
        Col::new(
            "debt_is_paid_in_kind",
            Ty::Boolean,
            true,
            "`Filing.body.nport.holdings[].debt_security.is_paid_in_kind`: optional bool: NULL when unset.",
        ),
        Col::new(
            "debt_is_mandatory_convertible",
            Ty::Boolean,
            true,
            "`Filing.body.nport.holdings[].debt_security.is_mandatory_convertible`: optional bool: NULL when unset.",
        ),
        Col::new(
            "debt_is_contingent_convertible",
            Ty::Boolean,
            true,
            "`Filing.body.nport.holdings[].debt_security.is_contingent_convertible`: optional bool: NULL when unset.",
        ),
        Col::new(
            "debt_delta",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].debt_security.delta`. `XXXX` (redacted) in public filings: text.",
        ),
        Col::new(
            "debt_reference_instrument_count",
            Ty::UInt32,
            false,
            "Derived from `Filing.body.nport.holdings[].debt_security.reference_instruments[]`: length of the list.",
        ),
        Col::new(
            "debt_conversion_currency_count",
            Ty::UInt32,
            false,
            "Derived from `Filing.body.nport.holdings[].debt_security.conversion_currencies[]`: length of the list.",
        ),
        Col::new(
            "has_derivative",
            Ty::Boolean,
            false,
            "Derived from `Filing.body.nport.holdings[].derivative`: `derivative` present. ~4% of holdings; details in `nport_derivatives`.",
        ),
        Col::new(
            "derivative_category",
            Ty::Utf8,
            true,
            "Derived from `Filing.body.nport.holdings[].derivative.category`: verbatim outer `derivative.category` (copy of nesting_level 0). `FWD`, `SWP`, `FUT`, `OPT`, `WAR`, `OTH`.",
        ),
        Col::new(
            "has_security_lending",
            Ty::Boolean,
            false,
            "Derived from `Filing.body.nport.holdings[].security_lending`: `security_lending` present.",
        ),
        Col::new(
            "lending_is_cash_collateral",
            Ty::Boolean,
            true,
            "`Filing.body.nport.holdings[].security_lending.is_cash_collateral`: proto bool; NULL when `security_lending` is absent.",
        ),
        Col::new(
            "lending_is_non_cash_collateral",
            Ty::Boolean,
            true,
            "`Filing.body.nport.holdings[].security_lending.is_non_cash_collateral`: proto bool; NULL when `security_lending` is absent.",
        ),
        Col::new(
            "lending_is_loan_by_fund",
            Ty::Boolean,
            true,
            "`Filing.body.nport.holdings[].security_lending.is_loan_by_fund`: proto bool; NULL when `security_lending` is absent.",
        ),
        Col::new(
            "lending_loan_value",
            Ty::Decimal(Family::N10),
            true,
            "`Filing.body.nport.holdings[].security_lending.loan_value`: decimal s=10 (§4.3, N10). USD.",
        ),
        Col::new(
            "lending_cash_collateral_value",
            Ty::Decimal(Family::N10),
            true,
            "`Filing.body.nport.holdings[].security_lending.cash_collateral_value`: decimal s=10 (§4.3, N10). USD.",
        ),
        Col::new(
            "has_parse_issues",
            Ty::Boolean,
            false,
            "Derived: true iff this row wrote ≥1 `parse_issues` row (§4.6).",
        ),
    ],
};

/// §3.27 `nport_debt_reference_instruments`.
pub(crate) const NPORT_DEBT_REFERENCE_INSTRUMENTS: TableSpec = TableSpec {
    name: super::NPORT_DEBT_REFERENCE_INSTRUMENTS,
    doc: "Reference instruments of convertible bonds (what they convert into).",
    filing_context: true,
    cols: &[
        Col::new(
            "series_id",
            Ty::Utf8,
            true,
            "Copy of `nport_reports.series_id`.",
        ),
        Col::new(
            "as_of_date",
            Ty::Date32,
            true,
            "Copy of `nport_reports.as_of_date`.",
        ),
        Col::new(
            "holding_index",
            Ty::UInt32,
            false,
            "Derived: position of the parent holding.",
        ),
        Col::new(
            "reference_index",
            Ty::UInt32,
            false,
            "Derived: position in `reference_instruments`.",
        ),
        Col::new(
            "reference_name",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].debt_security.reference_instruments[].name`.",
        ),
        Col::new(
            "reference_title",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].debt_security.reference_instruments[].title`.",
        ),
        Col::new(
            "currency",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].debt_security.reference_instruments[].currency`.",
        ),
        Col::new(
            "cusip",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].debt_security.reference_instruments[].cusip`.",
        ),
        Col::new(
            "cusip_norm",
            Ty::Utf8,
            true,
            "Derived from `Filing.body.nport.holdings[].debt_security.reference_instruments[].cusip`: §4.4 `cusip_norm`.",
        ),
        Col::new(
            "isin",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].debt_security.reference_instruments[].isin`.",
        ),
        Col::new(
            "ticker",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].debt_security.reference_instruments[].ticker`. The reference equity's ticker.",
        ),
        Col::new(
            "other_identifiers",
            Ty::ListStruct(&[("description", Member::Utf8), ("value", Member::Utf8)]),
            false,
            "`Filing.body.nport.holdings[].debt_security.reference_instruments[].other_identifiers[]`: one struct per element {description ← .description, value ← .value}, verbatim ('' → NULL); [] when empty.",
        ),
    ],
};

/// §3.28 `nport_debt_conversion_currencies`.
pub(crate) const NPORT_DEBT_CONVERSION_CURRENCIES: TableSpec = TableSpec {
    name: super::NPORT_DEBT_CONVERSION_CURRENCIES,
    doc: "Conversion terms of convertible bonds.",
    filing_context: true,
    cols: &[
        Col::new(
            "series_id",
            Ty::Utf8,
            true,
            "Copy of `nport_reports.series_id`.",
        ),
        Col::new(
            "as_of_date",
            Ty::Date32,
            true,
            "Copy of `nport_reports.as_of_date`.",
        ),
        Col::new(
            "holding_index",
            Ty::UInt32,
            false,
            "Derived: position of the parent holding.",
        ),
        Col::new(
            "conversion_index",
            Ty::UInt32,
            false,
            "Derived: position in `conversion_currencies`.",
        ),
        Col::new(
            "currency",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].debt_security.conversion_currencies[].currency`.",
        ),
        Col::new(
            "conversion_ratio",
            Ty::Decimal(Family::R12),
            true,
            "`Filing.body.nport.holdings[].debt_security.conversion_currencies[].conversion_ratio`: decimal s=12 (§4.3, R12). Shares per unit of principal.",
        ),
        Col::new(
            "has_parse_issues",
            Ty::Boolean,
            false,
            "Derived: true iff this row wrote ≥1 `parse_issues` row (§4.6).",
        ),
    ],
};

/// §3.29 `nport_derivatives`.
pub(crate) const NPORT_DERIVATIVES: TableSpec = TableSpec {
    name: super::NPORT_DERIVATIVES,
    doc: "Derivative terms of N-PORT positions; a nested derivative (the future under an option, the swap under a swaption) is its own row.",
    filing_context: true,
    cols: &[
        Col::new(
            "series_id",
            Ty::Utf8,
            true,
            "Copy of `nport_reports.series_id`.",
        ),
        Col::new(
            "as_of_date",
            Ty::Date32,
            true,
            "Copy of `nport_reports.as_of_date`.",
        ),
        Col::new(
            "holding_index",
            Ty::UInt32,
            false,
            "Derived: position of the parent holding.",
        ),
        Col::new(
            "nesting_level",
            Ty::UInt32,
            false,
            "Derived: 0 = `holdings[].derivative`; k = reached through k `.nested` hops. 1 = the future/forward/swap an option or swaption is on.",
        ),
        Col::new(
            "category",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.category`. `derivCat`: OPT, FWD, FUT, SWP, SWO, WAR, OTH.",
        ),
        Col::new(
            "counterparty_name",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.counterparty_name`.",
        ),
        Col::new(
            "counterparty_lei",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.counterparty_lei`.",
        ),
        Col::new(
            "put_or_call",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.put_or_call`.",
        ),
        Col::new(
            "written_or_purchased",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.written_or_purchased`.",
        ),
        Col::new(
            "payoff_profile",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.payoff_profile`. Futures: `Long`/`Short`.",
        ),
        Col::new(
            "ref_instrument_name",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.ref_instrument_name`.",
        ),
        Col::new(
            "ref_instrument_title",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.ref_instrument_title`.",
        ),
        Col::new(
            "ref_cusip",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.ref_cusip`.",
        ),
        Col::new(
            "ref_cusip_norm",
            Ty::Utf8,
            true,
            "Derived from `Filing.body.nport.holdings[].derivative(.nested)*.ref_cusip`: §4.4 `cusip_norm`.",
        ),
        Col::new(
            "ref_isin",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.ref_isin`.",
        ),
        Col::new(
            "ref_ticker",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.ref_ticker`.",
        ),
        Col::new(
            "ref_other_identifiers",
            Ty::ListStruct(&[("description", Member::Utf8), ("value", Member::Utf8)]),
            false,
            "`Filing.body.nport.holdings[].derivative(.nested)*.ref_other_identifiers[]`: one struct per element {description ← .description, value ← .value}, verbatim ('' → NULL); [] when empty.",
        ),
        Col::new(
            "ref_index_name",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.ref_index_name`.",
        ),
        Col::new(
            "ref_index_identifier",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.ref_index_identifier`.",
        ),
        Col::new(
            "ref_index_description",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.ref_index_description`.",
        ),
        Col::new(
            "other_description",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.other_description`. OthDeriv@othDesc, e.g. `rights`.",
        ),
        Col::new(
            "share_no",
            Ty::Decimal(Family::N10),
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.share_no`: decimal s=10 (§4.3, N10). Shares / contracts.",
        ),
        Col::new(
            "principal_amount",
            Ty::Decimal(Family::N10),
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.principal_amount`: decimal s=10 (§4.3, N10).",
        ),
        Col::new(
            "notional_amount",
            Ty::Decimal(Family::N10),
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.notional_amount`: decimal s=10 (§4.3, N10).",
        ),
        Col::new(
            "exercise_price",
            Ty::Decimal(Family::N10),
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.exercise_price`: decimal s=10 (§4.3, N10). In `exercise_currency`.",
        ),
        Col::new(
            "exercise_currency",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.exercise_currency`.",
        ),
        Col::new(
            "expiration_date",
            Ty::Date32,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.expiration_date`: date (§4.2). `2099-12-31` placeholders kept.",
        ),
        Col::new(
            "delta",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.delta`. `XXXX` (redacted) in public filings: text.",
        ),
        Col::new(
            "unrealized_appreciation",
            Ty::Decimal(Family::N10),
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.unrealized_appreciation`: decimal s=10 (§4.3, N10). USD.",
        ),
        Col::new(
            "currency",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.currency`. Futures, swaps.",
        ),
        Col::new(
            "termination_date",
            Ty::Date32,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.termination_date`: date (§4.2). Swaps.",
        ),
        Col::new(
            "amount_currency_sold",
            Ty::Decimal(Family::N10),
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.amount_currency_sold`: decimal s=10 (§4.3, N10). Forwards.",
        ),
        Col::new(
            "currency_sold",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.currency_sold`.",
        ),
        Col::new(
            "amount_currency_purchased",
            Ty::Decimal(Family::N10),
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.amount_currency_purchased`: decimal s=10 (§4.3, N10).",
        ),
        Col::new(
            "currency_purchased",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.currency_purchased`.",
        ),
        Col::new(
            "settlement_date",
            Ty::Date32,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.settlement_date`: date (§4.2). Forwards.",
        ),
        Col::new(
            "upfront_payment",
            Ty::Decimal(Family::N10),
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.upfront_payment`: decimal s=10 (§4.3, N10). Swaps.",
        ),
        Col::new(
            "upfront_receipt",
            Ty::Decimal(Family::N10),
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.upfront_receipt`: decimal s=10 (§4.3, N10).",
        ),
        Col::new(
            "payment_currency",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.payment_currency`.",
        ),
        Col::new(
            "receipt_currency",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.receipt_currency`.",
        ),
        Col::new(
            "swap_flag",
            Ty::Boolean,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.swap_flag`: Y/N text → bool (§4.1).",
        ),
        Col::new(
            "swap_leg_count",
            Ty::UInt32,
            false,
            "Derived from `Filing.body.nport.holdings[].derivative(.nested)*.legs[]`: length of the list.",
        ),
        Col::new(
            "index_component_count",
            Ty::UInt32,
            false,
            "Derived from `Filing.body.nport.holdings[].derivative(.nested)*.ref_index_components[]`: length of the list.",
        ),
        Col::new(
            "has_nested",
            Ty::Boolean,
            false,
            "Derived from `Filing.body.nport.holdings[].derivative(.nested)*.nested`: `nested` present (a row with nesting_level + 1 exists).",
        ),
        Col::new(
            "has_additional_info",
            Ty::Boolean,
            false,
            "Derived from `Filing.body.nport.holdings[].derivative(.nested)*.additional_info`: `additional_info` present (nested derivatives only).",
        ),
        Col::new(
            "addl_name",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.additional_info.name`.",
        ),
        Col::new(
            "addl_lei",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.additional_info.lei`.",
        ),
        Col::new(
            "addl_title",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.additional_info.title`.",
        ),
        Col::new(
            "addl_cusip",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.additional_info.cusip`.",
        ),
        Col::new(
            "addl_isin",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.additional_info.isin`.",
        ),
        Col::new(
            "addl_ticker",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.additional_info.ticker`.",
        ),
        Col::new(
            "addl_other_identifiers",
            Ty::ListStruct(&[("description", Member::Utf8), ("value", Member::Utf8)]),
            false,
            "`Filing.body.nport.holdings[].derivative(.nested)*.additional_info.other_identifiers[]`: one struct per element {description ← .description, value ← .value}, verbatim ('' → NULL); [] when empty.",
        ),
        Col::new(
            "addl_balance",
            Ty::Decimal(Family::N10),
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.additional_info.balance`: decimal s=10 (§4.3, N10).",
        ),
        Col::new(
            "addl_units",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.additional_info.units`.",
        ),
        Col::new(
            "addl_units_description",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.additional_info.units_description`.",
        ),
        Col::new(
            "addl_currency",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.additional_info.currency`.",
        ),
        Col::new(
            "addl_exchange_rate",
            Ty::Decimal(Family::R12),
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.additional_info.exchange_rate`: decimal s=12 (§4.3, R12).",
        ),
        Col::new(
            "addl_value_usd",
            Ty::Decimal(Family::N10),
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.additional_info.value_usd`: decimal s=10 (§4.3, N10).",
        ),
        Col::new(
            "addl_pct_value",
            Ty::Decimal(Family::R12),
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.additional_info.pct_value`: decimal s=12 (§4.3, R12).",
        ),
        Col::new(
            "addl_asset_category",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.additional_info.asset_category`.",
        ),
        Col::new(
            "addl_asset_category_description",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.additional_info.asset_category_description`.",
        ),
        Col::new(
            "addl_issuer_category",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.additional_info.issuer_category`.",
        ),
        Col::new(
            "addl_issuer_category_description",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.additional_info.issuer_category_description`.",
        ),
        Col::new(
            "addl_investment_country",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.additional_info.investment_country`.",
        ),
        Col::new(
            "addl_other_investment_country",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.additional_info.other_investment_country`.",
        ),
        Col::new(
            "has_parse_issues",
            Ty::Boolean,
            false,
            "Derived: true iff this row wrote ≥1 `parse_issues` row (§4.6).",
        ),
    ],
};

/// §3.30 `nport_derivative_swap_legs`.
pub(crate) const NPORT_DERIVATIVE_SWAP_LEGS: TableSpec = TableSpec {
    name: super::NPORT_DERIVATIVE_SWAP_LEGS,
    doc: "Pay and receive legs of swaps.",
    filing_context: true,
    cols: &[
        Col::new(
            "series_id",
            Ty::Utf8,
            true,
            "Copy of `nport_reports.series_id`.",
        ),
        Col::new(
            "as_of_date",
            Ty::Date32,
            true,
            "Copy of `nport_reports.as_of_date`.",
        ),
        Col::new(
            "holding_index",
            Ty::UInt32,
            false,
            "Derived: position of the parent holding.",
        ),
        Col::new(
            "nesting_level",
            Ty::UInt32,
            false,
            "Derived: nesting level of the parent derivative.",
        ),
        Col::new(
            "leg_index",
            Ty::UInt32,
            false,
            "Derived: position in `legs`.",
        ),
        Col::new(
            "leg_kind",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.legs[].kind`. Element name: `fixedPmntDesc`, `floatingRecDesc`, …",
        ),
        Col::new(
            "fixed_or_floating",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.legs[].fixed_or_floating`.",
        ),
        Col::new(
            "currency",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.legs[].currency`.",
        ),
        Col::new(
            "amount",
            Ty::Decimal(Family::N10),
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.legs[].amount`: decimal s=10 (§4.3, N10).",
        ),
        Col::new(
            "fixed_rate",
            Ty::Decimal(Family::R12),
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.legs[].fixed_rate`: decimal s=12 (§4.3, R12). Percent.",
        ),
        Col::new(
            "floating_rate_index",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.legs[].floating_rate_index`.",
        ),
        Col::new(
            "floating_rate_spread",
            Ty::Decimal(Family::R12),
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.legs[].floating_rate_spread`: decimal s=12 (§4.3, R12).",
        ),
        Col::new(
            "payment_amount",
            Ty::Decimal(Family::N10),
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.legs[].payment_amount`: decimal s=10 (§4.3, N10).",
        ),
        Col::new(
            "description",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.legs[].description`. `otherPmntDesc`/`otherRecDesc` text.",
        ),
        Col::new(
            "has_parse_issues",
            Ty::Boolean,
            false,
            "Derived: true iff this row wrote ≥1 `parse_issues` row (§4.6).",
        ),
    ],
};

/// §3.31 `nport_derivative_index_components`.
pub(crate) const NPORT_DERIVATIVE_INDEX_COMPONENTS: TableSpec = TableSpec {
    name: super::NPORT_DERIVATIVE_INDEX_COMPONENTS,
    doc: "Custom-basket components (one swap can list 30k+).",
    filing_context: true,
    cols: &[
        Col::new(
            "series_id",
            Ty::Utf8,
            true,
            "Copy of `nport_reports.series_id`.",
        ),
        Col::new(
            "as_of_date",
            Ty::Date32,
            true,
            "Copy of `nport_reports.as_of_date`.",
        ),
        Col::new(
            "holding_index",
            Ty::UInt32,
            false,
            "Derived: position of the parent holding.",
        ),
        Col::new(
            "nesting_level",
            Ty::UInt32,
            false,
            "Derived: nesting level of the parent derivative.",
        ),
        Col::new(
            "component_index",
            Ty::UInt32,
            false,
            "Derived: position in `ref_index_components`.",
        ),
        Col::new(
            "component_name",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.ref_index_components[].name`.",
        ),
        Col::new(
            "cusip",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.ref_index_components[].cusip`.",
        ),
        Col::new(
            "cusip_norm",
            Ty::Utf8,
            true,
            "Derived from `Filing.body.nport.holdings[].derivative(.nested)*.ref_index_components[].cusip`: §4.4 `cusip_norm`.",
        ),
        Col::new(
            "isin",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.ref_index_components[].isin`.",
        ),
        Col::new(
            "ticker",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.ref_index_components[].ticker`.",
        ),
        Col::new(
            "other_identifiers",
            Ty::ListStruct(&[("description", Member::Utf8), ("value", Member::Utf8)]),
            false,
            "`Filing.body.nport.holdings[].derivative(.nested)*.ref_index_components[].other_identifiers[]`: one struct per element {description ← .description, value ← .value}, verbatim ('' → NULL); [] when empty.",
        ),
        Col::new(
            "notional_amount",
            Ty::Decimal(Family::N10),
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.ref_index_components[].notional_amount`: decimal s=10 (§4.3, N10).",
        ),
        Col::new(
            "currency",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.ref_index_components[].currency`.",
        ),
        Col::new(
            "value",
            Ty::Decimal(Family::N10),
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.ref_index_components[].value`: decimal s=10 (§4.3, N10).",
        ),
        Col::new(
            "issue_currency",
            Ty::Utf8,
            true,
            "`Filing.body.nport.holdings[].derivative(.nested)*.ref_index_components[].issue_currency`.",
        ),
        Col::new(
            "has_parse_issues",
            Ty::Boolean,
            false,
            "Derived: true iff this row wrote ≥1 `parse_issues` row (§4.6).",
        ),
    ],
};
