//! Offline, network-free decode/map microbenchmark for a retained protobuf block.
//! Build identical source against the before/after generated bindings. On the old
//! revision replace `map_block_bytes(raw.clone(), ...)` with `map_block(raw, ...)`.
use anyhow::{ensure, Context, Result};
use blocks::{beacon, evm, solana};
use clap::{Parser, ValueEnum};
use firehose_parquet::{
    encode::EncodeBytes,
    traits::{BlockIdentity, BlockMapper},
};
use prost::{bytes::Bytes, Message};
use sha2::{Digest, Sha256};
use std::{collections::BTreeMap, hint::black_box, path::PathBuf, time::Instant};

#[derive(Clone, Copy, Debug, ValueEnum)]
enum Chain {
    Evm,
    Solana,
    Beacon,
}
#[derive(Parser)]
struct Args {
    #[arg(long, value_enum)]
    chain: Chain,
    #[arg(long)]
    block: PathBuf,
    #[arg(long, default_value_t = 500)]
    iterations: usize,
    /// Decode from &[u8] (copies), instead of owned Bytes (shares generated bytes fields).
    #[arg(long)]
    borrowed: bool,
}
fn decode<M: Message + Default>(raw: &Bytes, borrowed: bool) -> Result<M> {
    Ok(if borrowed {
        M::decode(raw.as_ref())?
    } else {
        M::decode(raw.clone())?
    })
}
fn mapper(chain: Chain) -> Box<dyn BlockMapper> {
    match chain {
        Chain::Evm => Box::new(evm::mapper::EvmBlockMapper::new(
            true,
            false,
            EncodeBytes::Binary,
            true,
        )),
        Chain::Solana => Box::new(solana::mapper::SolanaBlockMapper::new(
            true,
            false,
            EncodeBytes::Binary,
            false,
            true,
        )),
        Chain::Beacon => Box::new(beacon::mapper::BeaconBlockMapper::new(
            false,
            EncodeBytes::Binary,
        )),
    }
}
fn map(
    mapper: &mut dyn BlockMapper,
    raw: &Bytes,
    identity: &BlockIdentity,
    borrowed: bool,
) -> Result<u64> {
    if borrowed {
        mapper.map_block(raw.as_ref(), identity, None)
    } else {
        mapper.map_block_bytes(raw.clone(), identity, None)
    }
}
fn main() -> Result<()> {
    let args = Args::parse();
    ensure!(args.iterations > 0, "iterations must be positive");
    let raw = Bytes::from(std::fs::read(&args.block)?);
    let (height, seconds, nanos) = match args.chain {
        Chain::Evm => {
            let b: evm::proto::eth::Block = decode(&raw, args.borrowed)?;
            let t = b.header.context("header")?.timestamp.context("timestamp")?;
            (b.number, t.seconds, t.nanos)
        }
        Chain::Solana => {
            let b: solana::proto::solana::Block = decode(&raw, args.borrowed)?;
            (b.slot, b.block_time.map_or(0, |t| t.timestamp), 0)
        }
        Chain::Beacon => {
            let b: beacon::proto::beacon::Block = decode(&raw, args.borrowed)?;
            let t = b.timestamp.context("timestamp")?;
            (b.slot, t.seconds, t.nanos)
        }
    };
    let identity = BlockIdentity {
        block_num: height,
        parent_num: height.saturating_sub(1),
        timestamp: seconds,
        timestamp_nanos: nanos,
        ..Default::default()
    };
    let mut mapper = mapper(args.chain);
    // Full logical output digest and schemas are outside the timed region.
    map(mapper.as_mut(), &raw, &identity, args.borrowed)?;
    let mut output = BTreeMap::new();
    for (table, batch) in mapper.flush()? {
        let mut writer =
            arrow::ipc::writer::StreamWriter::try_new(Vec::new(), batch.schema().as_ref())?;
        writer.write(&batch)?;
        writer.finish()?;
        output.insert(table, serde_json::json!({"rows": batch.num_rows(), "schema": format!("{:?}", batch.schema()), "sha256": format!("{:x}", Sha256::digest(writer.into_inner()?))}));
    }
    // Warm allocator/caches equally. Each iteration flushes and drops all output.
    for _ in 0..10 {
        map(mapper.as_mut(), &raw, &identity, args.borrowed)?;
        black_box(mapper.flush()?);
    }
    let start = Instant::now();
    for _ in 0..args.iterations {
        match args.chain {
            Chain::Evm => {
                black_box(decode::<evm::proto::eth::Block>(&raw, args.borrowed)?);
            }
            Chain::Solana => {
                black_box(decode::<solana::proto::solana::Block>(&raw, args.borrowed)?);
            }
            Chain::Beacon => {
                black_box(decode::<beacon::proto::beacon::Block>(&raw, args.borrowed)?);
            }
        }
    }
    let decode_seconds = start.elapsed().as_secs_f64();
    let start = Instant::now();
    for _ in 0..args.iterations {
        black_box(map(mapper.as_mut(), &raw, &identity, args.borrowed)?);
        black_box(mapper.flush()?);
    }
    let map_flush_seconds = start.elapsed().as_secs_f64();
    println!(
        "{}",
        serde_json::json!({"chain":format!("{:?}",args.chain),"borrowed":args.borrowed,"iterations":args.iterations,"input_bytes":raw.len(),"input_sha256":format!("{:x}",Sha256::digest(&raw)),"decode_seconds":decode_seconds,"map_flush_seconds":map_flush_seconds,"output":output})
    );
    Ok(())
}
